DEFAULT_PROMPTS_EN = [
    {"text": "airplane", "quickdraw": "airplane"},
    {"text": "apple", "quickdraw": "apple"},
    {"text": "backpack", "quickdraw": "backpack"},
    {"text": "balloon", "quickdraw": "balloon"},
    {"text": "beach", "quickdraw": "beach"},
    {"text": "bear", "quickdraw": "bear"},
    {"text": "bicycle", "quickdraw": "bicycle"},
    {"text": "bird", "quickdraw": "bird"},
    {"text": "bridge", "quickdraw": "bridge"},
    {"text": "book", "quickdraw": "book"},
    {"text": "bus", "quickdraw": "bus"},
    {"text": "camera", "quickdraw": "camera"},
    {"text": "car", "quickdraw": "car"},
    {"text": "castle", "quickdraw": "castle"},
    {"text": "cat", "quickdraw": "cat"},
    {"text": "chair", "quickdraw": "chair"},
    {"text": "clock", "quickdraw": "clock"},
    {"text": "coffee", "quickdraw": "coffee cup"},
    {"text": "cookie", "quickdraw": "cookie"},
    {"text": "couch", "quickdraw": "couch"},
    {"text": "cow", "quickdraw": "cow"},
    {"text": "dinosaur", "quickdraw": "dinosaur"},
    {"text": "dog", "quickdraw": "dog"},
    {"text": "dragon", "quickdraw": "dragon"},
    {"text": "duck", "quickdraw": "duck"},
    {"text": "fish", "quickdraw": "fish"},
    {"text": "flower", "quickdraw": "flower"},
    {"text": "frog", "quickdraw": "frog"},
    {"text": "guitar", "quickdraw": "guitar"},
    {"text": "hamburger", "quickdraw": "hamburger"},
    {"text": "hat", "quickdraw": "hat"},
    {"text": "horse", "quickdraw": "horse"},
    {"text": "house", "quickdraw": "house"},
    {"text": "ice cream", "quickdraw": "ice cream"},
    {"text": "island", "quickdraw": "beach"},
    {"text": "key", "quickdraw": "key"},
    {"text": "kite", "quickdraw": "kite"},
    {"text": "lamp", "quickdraw": "lamp"},
    {"text": "laptop", "quickdraw": "laptop"},
    {"text": "monkey", "quickdraw": "monkey"},
    {"text": "mountain", "quickdraw": "mountain"},
    {"text": "octopus", "quickdraw": "octopus"},
    {"text": "panda", "quickdraw": "panda"},
    {"text": "piano", "quickdraw": "piano"},
    {"text": "pig", "quickdraw": "pig"},
    {"text": "pizza", "quickdraw": "pizza"},
    {"text": "rabbit", "quickdraw": "rabbit"},
    {"text": "rainbow", "quickdraw": "rainbow"},
    {"text": "robot", "quickdraw": "robot"},
    {"text": "rocket", "quickdraw": "rocket"},
    {"text": "sailboat", "quickdraw": "sailboat"},
    {"text": "sheep", "quickdraw": "sheep"},
    {"text": "snowman", "quickdraw": "snowman"},
    {"text": "spaceship", "quickdraw": "space ship"},
    {"text": "sun", "quickdraw": "sun"},
    {"text": "sunflower", "quickdraw": "sunflower"},
    {"text": "table", "quickdraw": "table"},
    {"text": "telescope", "quickdraw": "telescope"},
    {"text": "train", "quickdraw": "train"},
    {"text": "tree", "quickdraw": "tree"},
    {"text": "treehouse", "quickdraw": "house"},
    {"text": "umbrella", "quickdraw": "umbrella"},
    {"text": "whale", "quickdraw": "whale"},
]

DEFAULT_PROMPTS_ZH = [
    {"text": "飞机", "quickdraw": "airplane"},
    {"text": "苹果", "quickdraw": "apple"},
    {"text": "背包", "quickdraw": "backpack"},
    {"text": "气球", "quickdraw": "balloon"},
    {"text": "海滩", "quickdraw": "beach"},
    {"text": "熊", "quickdraw": "bear"},
    {"text": "自行车", "quickdraw": "bicycle"},
    {"text": "鸟", "quickdraw": "bird"},
    {"text": "桥", "quickdraw": "bridge"},
    {"text": "书", "quickdraw": "book"},
    {"text": "公交车", "quickdraw": "bus"},
    {"text": "相机", "quickdraw": "camera"},
    {"text": "汽车", "quickdraw": "car"},
    {"text": "城堡", "quickdraw": "castle"},
    {"text": "猫", "quickdraw": "cat"},
    {"text": "椅子", "quickdraw": "chair"},
    {"text": "时钟", "quickdraw": "clock"},
    {"text": "咖啡", "quickdraw": "coffee cup"},
    {"text": "饼干", "quickdraw": "cookie"},
    {"text": "沙发", "quickdraw": "couch"},
    {"text": "牛", "quickdraw": "cow"},
    {"text": "恐龙", "quickdraw": "dinosaur"},
    {"text": "狗", "quickdraw": "dog"},
    {"text": "龙", "quickdraw": "dragon"},
    {"text": "鸭子", "quickdraw": "duck"},
    {"text": "鱼", "quickdraw": "fish"},
    {"text": "花", "quickdraw": "flower"},
    {"text": "青蛙", "quickdraw": "frog"},
    {"text": "吉他", "quickdraw": "guitar"},
    {"text": "汉堡", "quickdraw": "hamburger"},
    {"text": "帽子", "quickdraw": "hat"},
    {"text": "马", "quickdraw": "horse"},
    {"text": "房子", "quickdraw": "house"},
    {"text": "冰淇淋", "quickdraw": "ice cream"},
    {"text": "岛屿", "quickdraw": "beach"},
    {"text": "钥匙", "quickdraw": "key"},
    {"text": "风筝", "quickdraw": "kite"},
    {"text": "灯", "quickdraw": "lamp"},
    {"text": "笔记本电脑", "quickdraw": "laptop"},
    {"text": "猴子", "quickdraw": "monkey"},
    {"text": "山", "quickdraw": "mountain"},
    {"text": "章鱼", "quickdraw": "octopus"},
    {"text": "熊猫", "quickdraw": "panda"},
    {"text": "钢琴", "quickdraw": "piano"},
    {"text": "猪", "quickdraw": "pig"},
    {"text": "披萨", "quickdraw": "pizza"},
    {"text": "兔子", "quickdraw": "rabbit"},
    {"text": "彩虹", "quickdraw": "rainbow"},
    {"text": "机器人", "quickdraw": "robot"},
    {"text": "火箭", "quickdraw": "rocket"},
    {"text": "帆船", "quickdraw": "sailboat"},
    {"text": "羊", "quickdraw": "sheep"},
    {"text": "雪人", "quickdraw": "snowman"},
    {"text": "宇宙飞船", "quickdraw": "space ship"},
    {"text": "太阳", "quickdraw": "sun"},
    {"text": "向日葵", "quickdraw": "sunflower"},
    {"text": "桌子", "quickdraw": "table"},
    {"text": "望远镜", "quickdraw": "telescope"},
    {"text": "火车", "quickdraw": "train"},
    {"text": "树", "quickdraw": "tree"},
    {"text": "树屋", "quickdraw": "house"},
    {"text": "雨伞", "quickdraw": "umbrella"},
    {"text": "鲸鱼", "quickdraw": "whale"},
]

DEFAULT_PROMPTS_BY_LANGUAGE = {
    "en": DEFAULT_PROMPTS_EN,
    "zh": DEFAULT_PROMPTS_ZH,
}

ENGLISH_ALIAS_OVERRIDES = {
    entry["text"]: entry["quickdraw"]
    for entry in DEFAULT_PROMPTS_EN
    if entry.get("quickdraw") and entry["quickdraw"] != entry["text"]
}

CHINESE_TO_QUICKDRAW = {
    entry["text"]: entry["quickdraw"]
    for entry in DEFAULT_PROMPTS_ZH
    if entry.get("quickdraw")
}
