DEFAULT_PROMPTS_EN = [
    {"text": "airplane", "quickdraw": "airplane"},
    {"text": "apple", "quickdraw": "apple"},
    {"text": "backpack", "quickdraw": "backpack"},
    {"text": "balloon", "quickdraw": "balloon"},
    {"text": "beach", "quickdraw": "beach"},
    {"text": "bear", "quickdraw": "bear"},
    {"text": "bicycle", "quickdraw": "bicycle"},
    {"text": "bird", "quickdraw": "bird"},
    {"text": "bridge", "quickdraw": "bridge"},
    {"text": "book", "quickdraw": "book"},
    {"text": "bus", "quickdraw": "bus"},
    {"text": "camera", "quickdraw": "camera"},
    {"text": "car", "quickdraw": "car"},
    {"text": "castle", "quickdraw": "castle"},
    {"text": "cat", "quickdraw": "cat"},
    {"text": "chair", "quickdraw": "chair"},
    {"text": "clock", "quickdraw": "clock"},
    {"text": "coffee", "quickdraw": "coffee cup"},
    {"text": "cookie", "quickdraw": "cookie"},
    {"text": "couch", "quickdraw": "couch"},
    {"text": "cow", "quickdraw": "cow"},
    {"text": "dinosaur", "quickdraw": "dinosaur"},
    {"text": "dog", "quickdraw": "dog"},
    {"text": "dragon", "quickdraw": "dragon"},
    {"text": "duck", "quickdraw": "duck"},
    {"text": "fish", "quickdraw": "fish"},
    {"text": "flower", "quickdraw": "flower"},
    {"text": "frog", "quickdraw": "frog"},
    {"text": "guitar", "quickdraw": "guitar"},
    {"text": "hamburger", "quickdraw": "hamburger"},
    {"text": "hat", "quickdraw": "hat"},
    {"text": "horse", "quickdraw": "horse"},
    {"text": "house", "quickdraw": "house"},
    {"text": "ice cream", "quickdraw": "ice cream"},
    {"text": "island", "quickdraw": "beach"},
    {"text": "key", "quickdraw": "key"},
    {"text": "kite", "quickdraw": "kite"},
    {"text": "lamp", "quickdraw": "lamp"},
    {"text": "laptop", "quickdraw": "laptop"},
    {"text": "monkey", "quickdraw": "monkey"},
    {"text": "mountain", "quickdraw": "mountain"},
    {"text": "octopus", "quickdraw": "octopus"},
    {"text": "panda", "quickdraw": "panda"},
    {"text": "piano", "quickdraw": "piano"},
    {"text": "pig", "quickdraw": "pig"},
    {"text": "pizza", "quickdraw": "pizza"},
    {"text": "rabbit", "quickdraw": "rabbit"},
    {"text": "rainbow", "quickdraw": "rainbow"},
    {"text": "robot", "quickdraw": "robot"},
    {"text": "rocket", "quickdraw": "rocket"},
    {"text": "sailboat", "quickdraw": "sailboat"},
    {"text": "sheep", "quickdraw": "sheep"},
    {"text": "snowman", "quickdraw": "snowman"},
    {"text": "spaceship", "quickdraw": "space ship"},
    {"text": "sun", "quickdraw": "sun"},
    {"text": "sunflower", "quickdraw": "sunflower"},
    {"text": "table", "quickdraw": "table"},
    {"text": "telescope", "quickdraw": "telescope"},
    {"text": "train", "quickdraw": "train"},
    {"text": "tree", "quickdraw": "tree"},
    {"text": "treehouse", "quickdraw": "house"},
    {"text": "umbrella", "quickdraw": "umbrella"},
    {"text": "whale", "quickdraw": "whale"},
    {"text": "alarm clock", "quickdraw": "alarm clock"},
    {"text": "ambulance", "quickdraw": "ambulance"},
    {"text": "angel", "quickdraw": "angel"},
    {"text": "ant", "quickdraw": "ant"},
    {"text": "axe", "quickdraw": "axe"},
    {"text": "banana", "quickdraw": "banana"},
    {"text": "basket", "quickdraw": "basket"},
    {"text": "baseball bat", "quickdraw": "baseball bat"},
    {"text": "bathtub", "quickdraw": "bathtub"},
    {"text": "bee", "quickdraw": "bee"},
    {"text": "belt", "quickdraw": "belt"},
    {"text": "bench", "quickdraw": "bench"},
    {"text": "binoculars", "quickdraw": "binoculars"},
    {"text": "birthday cake", "quickdraw": "birthday cake"},
    {"text": "boomerang", "quickdraw": "boomerang"},
    {"text": "bowtie", "quickdraw": "bowtie"},
    {"text": "broccoli", "quickdraw": "broccoli"},
    {"text": "broom", "quickdraw": "broom"},
    {"text": "bulldozer", "quickdraw": "bulldozer"},
    {"text": "cactus", "quickdraw": "cactus"},
    {"text": "candle", "quickdraw": "candle"},
    {"text": "canoe", "quickdraw": "canoe"},
    {"text": "cello", "quickdraw": "cello"},
    {"text": "crown", "quickdraw": "crown"},
    {"text": "diamond", "quickdraw": "diamond"},
    {"text": "dolphin", "quickdraw": "dolphin"},
    {"text": "donut", "quickdraw": "donut"},
    {"text": "door", "quickdraw": "door"},
    {"text": "ear", "quickdraw": "ear"},
    {"text": "feather", "quickdraw": "feather"},
    {"text": "fire hydrant", "quickdraw": "fire hydrant"},
    {"text": "flamingo", "quickdraw": "flamingo"},
    {"text": "giraffe", "quickdraw": "giraffe"},
    {"text": "hedgehog", "quickdraw": "hedgehog"},
    {"text": "helicopter", "quickdraw": "helicopter"},
    {"text": "kangaroo", "quickdraw": "kangaroo"},
    {"text": "ladder", "quickdraw": "ladder"},
    {"text": "leaf", "quickdraw": "leaf"},
    {"text": "lighthouse", "quickdraw": "lighthouse"},
    {"text": "lollipop", "quickdraw": "lollipop"},
    {"text": "microphone", "quickdraw": "microphone"},
    {"text": "mushroom", "quickdraw": "mushroom"},
    {"text": "owl", "quickdraw": "owl"},
    {"text": "parrot", "quickdraw": "parrot"},
    {"text": "penguin", "quickdraw": "penguin"},
    {"text": "pineapple", "quickdraw": "pineapple"},
    {"text": "scissors", "quickdraw": "scissors"},
    {"text": "shark", "quickdraw": "shark"},
    {"text": "strawberry", "quickdraw": "strawberry"},
    {"text": "zebra", "quickdraw": "zebra"},
    {"text": "aircraft carrier", "quickdraw": "aircraft carrier"},
    {"text": "anvil", "quickdraw": "anvil"},
    {"text": "arm", "quickdraw": "arm"},
    {"text": "asparagus", "quickdraw": "asparagus"},
    {"text": "baseball", "quickdraw": "baseball"},
    {"text": "basketball", "quickdraw": "basketball"},
    {"text": "bat", "quickdraw": "bat"},
    {"text": "beard", "quickdraw": "beard"},
    {"text": "bed", "quickdraw": "bed"},
    {"text": "blackberry", "quickdraw": "blackberry"},
    {"text": "blueberry", "quickdraw": "blueberry"},
    {"text": "bottlecap", "quickdraw": "bottlecap"},
    {"text": "bracelet", "quickdraw": "bracelet"},
    {"text": "brain", "quickdraw": "brain"},
    {"text": "bread", "quickdraw": "bread"},
    {"text": "bucket", "quickdraw": "bucket"},
    {"text": "bush", "quickdraw": "bush"},
    {"text": "butterfly", "quickdraw": "butterfly"},
    {"text": "cake", "quickdraw": "cake"},
    {"text": "calculator", "quickdraw": "calculator"},
    {"text": "calendar", "quickdraw": "calendar"},
    {"text": "camel", "quickdraw": "camel"},
    {"text": "camouflage", "quickdraw": "camouflage"},
    {"text": "campfire", "quickdraw": "campfire"},
    {"text": "cannon", "quickdraw": "cannon"},
    {"text": "carrot", "quickdraw": "carrot"},
    {"text": "ceiling fan", "quickdraw": "ceiling fan"},
    {"text": "cell phone", "quickdraw": "cell phone"},
    {"text": "chandelier", "quickdraw": "chandelier"},
    {"text": "church", "quickdraw": "church"},
    {"text": "circle", "quickdraw": "circle"},
    {"text": "clarinet", "quickdraw": "clarinet"},
    {"text": "cloud", "quickdraw": "cloud"},
    {"text": "compass", "quickdraw": "compass"},
    {"text": "computer", "quickdraw": "computer"},
    {"text": "cooler", "quickdraw": "cooler"},
    {"text": "crab", "quickdraw": "crab"},
    {"text": "crayon", "quickdraw": "crayon"},
    {"text": "crocodile", "quickdraw": "crocodile"},
    {"text": "cruise ship", "quickdraw": "cruise ship"},
    {"text": "cup", "quickdraw": "cup"},
    {"text": "dishwasher", "quickdraw": "dishwasher"},
    {"text": "diving board", "quickdraw": "diving board"},
    {"text": "dresser", "quickdraw": "dresser"},
    {"text": "drill", "quickdraw": "drill"},
    {"text": "drums", "quickdraw": "drums"},
    {"text": "dumbbell", "quickdraw": "dumbbell"},
    {"text": "elbow", "quickdraw": "elbow"},
    {"text": "elephant", "quickdraw": "elephant"},
    {"text": "envelope", "quickdraw": "envelope"},
    {"text": "eraser", "quickdraw": "eraser"},
    {"text": "eye", "quickdraw": "eye"},
    {"text": "eyeglasses", "quickdraw": "eyeglasses"},
    {"text": "face", "quickdraw": "face"},
    {"text": "fan", "quickdraw": "fan"},
    {"text": "fence", "quickdraw": "fence"},
    {"text": "finger", "quickdraw": "finger"},
    {"text": "fireplace", "quickdraw": "fireplace"},
    {"text": "firetruck", "quickdraw": "firetruck"},
    {"text": "flashlight", "quickdraw": "flashlight"},
    {"text": "flip flops", "quickdraw": "flip flops"},
    {"text": "floor lamp", "quickdraw": "floor lamp"},
    {"text": "flying saucer", "quickdraw": "flying saucer"},
    {"text": "foot", "quickdraw": "foot"},
    {"text": "fork", "quickdraw": "fork"},
    {"text": "frying pan", "quickdraw": "frying pan"},
    {"text": "garden", "quickdraw": "garden"},
    {"text": "garden hose", "quickdraw": "garden hose"},
    {"text": "goatee", "quickdraw": "goatee"},
    {"text": "golf club", "quickdraw": "golf club"},
    {"text": "grapes", "quickdraw": "grapes"},
    {"text": "grass", "quickdraw": "grass"},
    {"text": "hammer", "quickdraw": "hammer"},
    {"text": "hand", "quickdraw": "hand"},
    {"text": "harp", "quickdraw": "harp"},
    {"text": "headphones", "quickdraw": "headphones"},
    {"text": "helmet", "quickdraw": "helmet"},
    {"text": "hexagon", "quickdraw": "hexagon"},
    {"text": "hockey stick", "quickdraw": "hockey stick"},
    {"text": "hospital", "quickdraw": "hospital"},
    {"text": "hot air balloon", "quickdraw": "hot air balloon"},
    {"text": "hot dog", "quickdraw": "hot dog"},
    {"text": "hot tub", "quickdraw": "hot tub"},
    {"text": "hourglass", "quickdraw": "hourglass"},
    {"text": "house plant", "quickdraw": "house plant"},
    {"text": "hurricane", "quickdraw": "hurricane"},
    {"text": "jacket", "quickdraw": "jacket"},
    {"text": "jail", "quickdraw": "jail"},
    {"text": "keyboard", "quickdraw": "keyboard"},
    {"text": "knee", "quickdraw": "knee"},
    {"text": "knife", "quickdraw": "knife"},
    {"text": "leg", "quickdraw": "leg"},
    {"text": "light bulb", "quickdraw": "light bulb"},
    {"text": "lightning", "quickdraw": "lightning"},
    {"text": "line", "quickdraw": "line"},
    {"text": "lion", "quickdraw": "lion"},
    {"text": "lipstick", "quickdraw": "lipstick"},
    {"text": "lobster", "quickdraw": "lobster"},
    {"text": "mailbox", "quickdraw": "mailbox"},
    {"text": "map", "quickdraw": "map"},
    {"text": "air conditioner", "quickdraw": "air conditioner"},
    {"text": "animal migration", "quickdraw": "animal migration"},
    {"text": "bandage", "quickdraw": "bandage"},
    {"text": "barn", "quickdraw": "barn"},
    {"text": "dish", "quickdraw": "dish"},
    {"text": "marker", "quickdraw": "marker"},
    {"text": "matches", "quickdraw": "matches"},
    {"text": "megaphone", "quickdraw": "megaphone"},
    {"text": "mermaid", "quickdraw": "mermaid"},
    {"text": "microwave", "quickdraw": "microwave"},
    {"text": "moon", "quickdraw": "moon"},
    {"text": "mosquito", "quickdraw": "mosquito"},
    {"text": "motorbike", "quickdraw": "motorbike"},
    {"text": "mouse", "quickdraw": "mouse"},
    {"text": "mouth", "quickdraw": "mouth"},
    {"text": "moustache", "quickdraw": "moustache"},
    {"text": "mug", "quickdraw": "mug"},
    {"text": "nail", "quickdraw": "nail"},
    {"text": "necklace", "quickdraw": "necklace"},
    {"text": "nose", "quickdraw": "nose"},
    {"text": "ocean", "quickdraw": "ocean"},
    {"text": "octagon", "quickdraw": "octagon"},
    {"text": "onion", "quickdraw": "onion"},
    {"text": "oven", "quickdraw": "oven"},
    {"text": "paintbrush", "quickdraw": "paintbrush"},
    {"text": "paint can", "quickdraw": "paint can"},
    {"text": "palm tree", "quickdraw": "palm tree"},
    {"text": "pants", "quickdraw": "pants"},
    {"text": "paper clip", "quickdraw": "paper clip"},
    {"text": "parachute", "quickdraw": "parachute"},
    {"text": "pear", "quickdraw": "pear"},
    {"text": "peas", "quickdraw": "peas"},
    {"text": "pencil", "quickdraw": "pencil"},
    {"text": "pickup truck", "quickdraw": "pickup truck"},
    {"text": "picture frame", "quickdraw": "picture frame"},
    {"text": "pillow", "quickdraw": "pillow"},
    {"text": "pliers", "quickdraw": "pliers"},
    {"text": "police car", "quickdraw": "police car"},
    {"text": "pond", "quickdraw": "pond"},
    {"text": "pool", "quickdraw": "pool"},
    {"text": "popsicle", "quickdraw": "popsicle"},
    {"text": "postcard", "quickdraw": "postcard"},
    {"text": "potato", "quickdraw": "potato"},
    {"text": "power outlet", "quickdraw": "power outlet"},
    {"text": "purse", "quickdraw": "purse"},
    {"text": "raccoon", "quickdraw": "raccoon"},
    {"text": "radio", "quickdraw": "radio"},
    {"text": "rain", "quickdraw": "rain"},
    {"text": "rake", "quickdraw": "rake"},
    {"text": "remote control", "quickdraw": "remote control"},
    {"text": "rhinoceros", "quickdraw": "rhinoceros"},
    {"text": "rifle", "quickdraw": "rifle"},
    {"text": "river", "quickdraw": "river"},
    {"text": "roller coaster", "quickdraw": "roller coaster"},
    {"text": "rollerskates", "quickdraw": "rollerskates"},
    {"text": "sandwich", "quickdraw": "sandwich"},
    {"text": "saw", "quickdraw": "saw"},
    {"text": "saxophone", "quickdraw": "saxophone"},
    {"text": "school bus", "quickdraw": "school bus"},
    {"text": "scorpion", "quickdraw": "scorpion"},
    {"text": "screwdriver", "quickdraw": "screwdriver"},
    {"text": "sea turtle", "quickdraw": "sea turtle"},
    {"text": "see saw", "quickdraw": "see saw"},
    {"text": "shoe", "quickdraw": "shoe"},
    {"text": "shorts", "quickdraw": "shorts"},
    {"text": "shovel", "quickdraw": "shovel"},
    {"text": "sink", "quickdraw": "sink"},
    {"text": "skateboard", "quickdraw": "skateboard"},
    {"text": "skull", "quickdraw": "skull"},
    {"text": "skyscraper", "quickdraw": "skyscraper"},
    {"text": "sleeping bag", "quickdraw": "sleeping bag"},
    {"text": "smiley face", "quickdraw": "smiley face"},
    {"text": "snail", "quickdraw": "snail"},
    {"text": "snake", "quickdraw": "snake"},
    {"text": "snorkel", "quickdraw": "snorkel"},
    {"text": "snowflake", "quickdraw": "snowflake"},
    {"text": "soccer ball", "quickdraw": "soccer ball"},
    {"text": "sock", "quickdraw": "sock"},
    {"text": "speedboat", "quickdraw": "speedboat"},
    {"text": "spider", "quickdraw": "spider"},
    {"text": "spoon", "quickdraw": "spoon"},
    {"text": "spreadsheet", "quickdraw": "spreadsheet"},
    {"text": "square", "quickdraw": "square"},
    {"text": "squiggle", "quickdraw": "squiggle"},
    {"text": "squirrel", "quickdraw": "squirrel"},
    {"text": "staircase", "quickdraw": "staircase"},
    {"text": "star", "quickdraw": "star"},
    {"text": "steak", "quickdraw": "steak"},
    {"text": "stereo", "quickdraw": "stereo"},
    {"text": "stethoscope", "quickdraw": "stethoscope"},
    {"text": "stitches", "quickdraw": "stitches"},
    {"text": "stop sign", "quickdraw": "stop sign"},
    {"text": "stove", "quickdraw": "stove"},
    {"text": "streetlight", "quickdraw": "streetlight"},
    {"text": "string bean", "quickdraw": "string bean"},
    {"text": "submarine", "quickdraw": "submarine"},
    {"text": "suitcase", "quickdraw": "suitcase"},
    {"text": "swan", "quickdraw": "swan"},
    {"text": "sweater", "quickdraw": "sweater"},
    {"text": "swing set", "quickdraw": "swing set"},
    {"text": "hockey puck", "quickdraw": "hockey puck"},
    {"text": "lantern", "quickdraw": "lantern"},
    {"text": "lighter", "quickdraw": "lighter"},
    {"text": "passport", "quickdraw": "passport"},
    {"text": "peanut", "quickdraw": "peanut"},
    {"text": "stairs", "quickdraw": "stairs"},
    {"text": "sword", "quickdraw": "sword"},
    {"text": "syringe", "quickdraw": "syringe"},
    {"text": "t-shirt", "quickdraw": "t-shirt"},
    {"text": "teapot", "quickdraw": "teapot"},
    {"text": "teddy-bear", "quickdraw": "teddy-bear"},
    {"text": "telephone", "quickdraw": "telephone"},
    {"text": "television", "quickdraw": "television"},
    {"text": "tennis racquet", "quickdraw": "tennis racquet"},
    {"text": "tent", "quickdraw": "tent"},
    {"text": "The Eiffel Tower", "quickdraw": "The Eiffel Tower"},
    {"text": "The Great Wall of China", "quickdraw": "The Great Wall of China"},
    {"text": "The Mona Lisa", "quickdraw": "The Mona Lisa"},
    {"text": "tiger", "quickdraw": "tiger"},
    {"text": "toaster", "quickdraw": "toaster"},
    {"text": "toe", "quickdraw": "toe"},
    {"text": "toilet", "quickdraw": "toilet"},
    {"text": "tooth", "quickdraw": "tooth"},
    {"text": "toothbrush", "quickdraw": "toothbrush"},
    {"text": "toothpaste", "quickdraw": "toothpaste"},
    {"text": "tornado", "quickdraw": "tornado"},
    {"text": "tractor", "quickdraw": "tractor"},
    {"text": "traffic light", "quickdraw": "traffic light"},
    {"text": "triangle", "quickdraw": "triangle"},
    {"text": "trombone", "quickdraw": "trombone"},
    {"text": "truck", "quickdraw": "truck"},
    {"text": "trumpet", "quickdraw": "trumpet"},
    {"text": "underwear", "quickdraw": "underwear"},
    {"text": "van", "quickdraw": "van"},
    {"text": "vase", "quickdraw": "vase"},
    {"text": "violin", "quickdraw": "violin"},
    {"text": "washing machine", "quickdraw": "washing machine"},
    {"text": "watermelon", "quickdraw": "watermelon"},
    {"text": "waterslide", "quickdraw": "waterslide"},
    {"text": "wheel", "quickdraw": "wheel"},
    {"text": "windmill", "quickdraw": "windmill"},
    {"text": "wine bottle", "quickdraw": "wine bottle"},
    {"text": "wine glass", "quickdraw": "wine glass"},
    {"text": "wristwatch", "quickdraw": "wristwatch"},
    {"text": "yoga", "quickdraw": "yoga"},
    {"text": "zigzag", "quickdraw": "zigzag"},
]

DEFAULT_PROMPTS_ZH = [
    {"text": "飞机", "quickdraw": "airplane"},
    {"text": "苹果", "quickdraw": "apple"},
    {"text": "背包", "quickdraw": "backpack"},
    {"text": "气球", "quickdraw": "balloon"},
    {"text": "海滩", "quickdraw": "beach"},
    {"text": "熊", "quickdraw": "bear"},
    {"text": "自行车", "quickdraw": "bicycle"},
    {"text": "鸟", "quickdraw": "bird"},
    {"text": "桥", "quickdraw": "bridge"},
    {"text": "书", "quickdraw": "book"},
    {"text": "公交车", "quickdraw": "bus"},
    {"text": "相机", "quickdraw": "camera"},
    {"text": "汽车", "quickdraw": "car"},
    {"text": "城堡", "quickdraw": "castle"},
    {"text": "猫", "quickdraw": "cat"},
    {"text": "椅子", "quickdraw": "chair"},
    {"text": "时钟", "quickdraw": "clock"},
    {"text": "咖啡", "quickdraw": "coffee cup"},
    {"text": "饼干", "quickdraw": "cookie"},
    {"text": "沙发", "quickdraw": "couch"},
    {"text": "牛", "quickdraw": "cow"},
    {"text": "恐龙", "quickdraw": "dinosaur"},
    {"text": "狗", "quickdraw": "dog"},
    {"text": "龙", "quickdraw": "dragon"},
    {"text": "鸭子", "quickdraw": "duck"},
    {"text": "鱼", "quickdraw": "fish"},
    {"text": "花", "quickdraw": "flower"},
    {"text": "青蛙", "quickdraw": "frog"},
    {"text": "吉他", "quickdraw": "guitar"},
    {"text": "汉堡", "quickdraw": "hamburger"},
    {"text": "帽子", "quickdraw": "hat"},
    {"text": "马", "quickdraw": "horse"},
    {"text": "房子", "quickdraw": "house"},
    {"text": "冰淇淋", "quickdraw": "ice cream"},
    {"text": "岛屿", "quickdraw": "beach"},
    {"text": "钥匙", "quickdraw": "key"},
    {"text": "风筝", "quickdraw": "kite"},
    {"text": "灯", "quickdraw": "lamp"},
    {"text": "笔记本电脑", "quickdraw": "laptop"},
    {"text": "猴子", "quickdraw": "monkey"},
    {"text": "山", "quickdraw": "mountain"},
    {"text": "章鱼", "quickdraw": "octopus"},
    {"text": "熊猫", "quickdraw": "panda"},
    {"text": "钢琴", "quickdraw": "piano"},
    {"text": "猪", "quickdraw": "pig"},
    {"text": "披萨", "quickdraw": "pizza"},
    {"text": "兔子", "quickdraw": "rabbit"},
    {"text": "彩虹", "quickdraw": "rainbow"},
    {"text": "机器人", "quickdraw": "robot"},
    {"text": "火箭", "quickdraw": "rocket"},
    {"text": "帆船", "quickdraw": "sailboat"},
    {"text": "羊", "quickdraw": "sheep"},
    {"text": "雪人", "quickdraw": "snowman"},
    {"text": "宇宙飞船", "quickdraw": "space ship"},
    {"text": "太阳", "quickdraw": "sun"},
    {"text": "向日葵", "quickdraw": "sunflower"},
    {"text": "桌子", "quickdraw": "table"},
    {"text": "望远镜", "quickdraw": "telescope"},
    {"text": "火车", "quickdraw": "train"},
    {"text": "树", "quickdraw": "tree"},
    {"text": "树屋", "quickdraw": "house"},
    {"text": "雨伞", "quickdraw": "umbrella"},
    {"text": "鲸鱼", "quickdraw": "whale"},
    {"text": "闹钟", "quickdraw": "alarm clock"},
    {"text": "救护车", "quickdraw": "ambulance"},
    {"text": "天使", "quickdraw": "angel"},
    {"text": "蚂蚁", "quickdraw": "ant"},
    {"text": "斧头", "quickdraw": "axe"},
    {"text": "香蕉", "quickdraw": "banana"},
    {"text": "篮子", "quickdraw": "basket"},
    {"text": "棒球棒", "quickdraw": "baseball bat"},
    {"text": "浴缸", "quickdraw": "bathtub"},
    {"text": "蜜蜂", "quickdraw": "bee"},
    {"text": "皮带", "quickdraw": "belt"},
    {"text": "长椅", "quickdraw": "bench"},
    {"text": "双筒望远镜", "quickdraw": "binoculars"},
    {"text": "生日蛋糕", "quickdraw": "birthday cake"},
    {"text": "回旋镖", "quickdraw": "boomerang"},
    {"text": "领结", "quickdraw": "bowtie"},
    {"text": "西兰花", "quickdraw": "broccoli"},
    {"text": "扫帚", "quickdraw": "broom"},
    {"text": "推土机", "quickdraw": "bulldozer"},
    {"text": "仙人掌", "quickdraw": "cactus"},
    {"text": "蜡烛", "quickdraw": "candle"},
    {"text": "独木舟", "quickdraw": "canoe"},
    {"text": "大提琴", "quickdraw": "cello"},
    {"text": "王冠", "quickdraw": "crown"},
    {"text": "钻石", "quickdraw": "diamond"},
    {"text": "海豚", "quickdraw": "dolphin"},
    {"text": "甜甜圈", "quickdraw": "donut"},
    {"text": "门", "quickdraw": "door"},
    {"text": "耳朵", "quickdraw": "ear"},
    {"text": "羽毛", "quickdraw": "feather"},
    {"text": "消防栓", "quickdraw": "fire hydrant"},
    {"text": "火烈鸟", "quickdraw": "flamingo"},
    {"text": "长颈鹿", "quickdraw": "giraffe"},
    {"text": "刺猬", "quickdraw": "hedgehog"},
    {"text": "直升机", "quickdraw": "helicopter"},
    {"text": "袋鼠", "quickdraw": "kangaroo"},
    {"text": "梯子", "quickdraw": "ladder"},
    {"text": "叶子", "quickdraw": "leaf"},
    {"text": "灯塔", "quickdraw": "lighthouse"},
    {"text": "棒棒糖", "quickdraw": "lollipop"},
    {"text": "麦克风", "quickdraw": "microphone"},
    {"text": "蘑菇", "quickdraw": "mushroom"},
    {"text": "猫头鹰", "quickdraw": "owl"},
    {"text": "鹦鹉", "quickdraw": "parrot"},
    {"text": "企鹅", "quickdraw": "penguin"},
    {"text": "菠萝", "quickdraw": "pineapple"},
    {"text": "剪刀", "quickdraw": "scissors"},
    {"text": "鲨鱼", "quickdraw": "shark"},
    {"text": "草莓", "quickdraw": "strawberry"},
    {"text": "斑马", "quickdraw": "zebra"},
    {"text": "航空母舰", "quickdraw": "aircraft carrier"},
    {"text": "铁砧", "quickdraw": "anvil"},
    {"text": "手臂", "quickdraw": "arm"},
    {"text": "芦笋", "quickdraw": "asparagus"},
    {"text": "棒球", "quickdraw": "baseball"},
    {"text": "篮球", "quickdraw": "basketball"},
    {"text": "蝙蝠", "quickdraw": "bat"},
    {"text": "胡子", "quickdraw": "beard"},
    {"text": "床", "quickdraw": "bed"},
    {"text": "黑莓", "quickdraw": "blackberry"},
    {"text": "蓝莓", "quickdraw": "blueberry"},
    {"text": "瓶盖", "quickdraw": "bottlecap"},
    {"text": "手链", "quickdraw": "bracelet"},
    {"text": "大脑", "quickdraw": "brain"},
    {"text": "面包", "quickdraw": "bread"},
    {"text": "桶", "quickdraw": "bucket"},
    {"text": "灌木丛", "quickdraw": "bush"},
    {"text": "蝴蝶", "quickdraw": "butterfly"},
    {"text": "蛋糕", "quickdraw": "cake"},
    {"text": "计算器", "quickdraw": "calculator"},
    {"text": "日历", "quickdraw": "calendar"},
    {"text": "骆驼", "quickdraw": "camel"},
    {"text": "迷彩", "quickdraw": "camouflage"},
    {"text": "篝火", "quickdraw": "campfire"},
    {"text": "大炮", "quickdraw": "cannon"},
    {"text": "胡萝卜", "quickdraw": "carrot"},
    {"text": "吊扇", "quickdraw": "ceiling fan"},
    {"text": "手机", "quickdraw": "cell phone"},
    {"text": "吊灯", "quickdraw": "chandelier"},
    {"text": "教堂", "quickdraw": "church"},
    {"text": "圆形", "quickdraw": "circle"},
    {"text": "单簧管", "quickdraw": "clarinet"},
    {"text": "云", "quickdraw": "cloud"},
    {"text": "指南针", "quickdraw": "compass"},
    {"text": "电脑", "quickdraw": "computer"},
    {"text": "保温箱", "quickdraw": "cooler"},
    {"text": "螃蟹", "quickdraw": "crab"},
    {"text": "蜡笔", "quickdraw": "crayon"},
    {"text": "鳄鱼", "quickdraw": "crocodile"},
    {"text": "邮轮", "quickdraw": "cruise ship"},
    {"text": "杯子", "quickdraw": "cup"},
    {"text": "洗碗机", "quickdraw": "dishwasher"},
    {"text": "跳水板", "quickdraw": "diving board"},
    {"text": "抽屉柜", "quickdraw": "dresser"},
    {"text": "电钻", "quickdraw": "drill"},
    {"text": "架子鼓", "quickdraw": "drums"},
    {"text": "哑铃", "quickdraw": "dumbbell"},
    {"text": "手肘", "quickdraw": "elbow"},
    {"text": "大象", "quickdraw": "elephant"},
    {"text": "信封", "quickdraw": "envelope"},
    {"text": "橡皮擦", "quickdraw": "eraser"},
    {"text": "眼睛", "quickdraw": "eye"},
    {"text": "眼镜", "quickdraw": "eyeglasses"},
    {"text": "脸", "quickdraw": "face"},
    {"text": "风扇", "quickdraw": "fan"},
    {"text": "栅栏", "quickdraw": "fence"},
    {"text": "手指", "quickdraw": "finger"},
    {"text": "壁炉", "quickdraw": "fireplace"},
    {"text": "消防车", "quickdraw": "firetruck"},
    {"text": "手电筒", "quickdraw": "flashlight"},
    {"text": "人字拖", "quickdraw": "flip flops"},
    {"text": "落地灯", "quickdraw": "floor lamp"},
    {"text": "飞碟", "quickdraw": "flying saucer"},
    {"text": "脚", "quickdraw": "foot"},
    {"text": "叉子", "quickdraw": "fork"},
    {"text": "平底锅", "quickdraw": "frying pan"},
    {"text": "花园", "quickdraw": "garden"},
    {"text": "花园水管", "quickdraw": "garden hose"},
    {"text": "山羊胡", "quickdraw": "goatee"},
    {"text": "高尔夫球杆", "quickdraw": "golf club"},
    {"text": "葡萄", "quickdraw": "grapes"},
    {"text": "草", "quickdraw": "grass"},
    {"text": "锤子", "quickdraw": "hammer"},
    {"text": "手", "quickdraw": "hand"},
    {"text": "竖琴", "quickdraw": "harp"},
    {"text": "耳机", "quickdraw": "headphones"},
    {"text": "头盔", "quickdraw": "helmet"},
    {"text": "六边形", "quickdraw": "hexagon"},
    {"text": "曲棍球棒", "quickdraw": "hockey stick"},
    {"text": "医院", "quickdraw": "hospital"},
    {"text": "热气球", "quickdraw": "hot air balloon"},
    {"text": "热狗", "quickdraw": "hot dog"},
    {"text": "热水浴缸", "quickdraw": "hot tub"},
    {"text": "沙漏", "quickdraw": "hourglass"},
    {"text": "盆栽", "quickdraw": "house plant"},
    {"text": "飓风", "quickdraw": "hurricane"},
    {"text": "夹克", "quickdraw": "jacket"},
    {"text": "监狱", "quickdraw": "jail"},
    {"text": "键盘", "quickdraw": "keyboard"},
    {"text": "膝盖", "quickdraw": "knee"},
    {"text": "刀", "quickdraw": "knife"},
    {"text": "腿", "quickdraw": "leg"},
    {"text": "灯泡", "quickdraw": "light bulb"},
    {"text": "闪电", "quickdraw": "lightning"},
    {"text": "线", "quickdraw": "line"},
    {"text": "狮子", "quickdraw": "lion"},
    {"text": "口红", "quickdraw": "lipstick"},
    {"text": "龙虾", "quickdraw": "lobster"},
    {"text": "邮箱", "quickdraw": "mailbox"},
    {"text": "地图", "quickdraw": "map"},
    {"text": "空调", "quickdraw": "air conditioner"},
    {"text": "动物迁徙", "quickdraw": "animal migration"},
    {"text": "绷带", "quickdraw": "bandage"},
    {"text": "谷仓", "quickdraw": "barn"},
    {"text": "盘子", "quickdraw": "dish"},
    {"text": "马克笔", "quickdraw": "marker"},
    {"text": "火柴", "quickdraw": "matches"},
    {"text": "扩音器", "quickdraw": "megaphone"},
    {"text": "美人鱼", "quickdraw": "mermaid"},
    {"text": "微波炉", "quickdraw": "microwave"},
    {"text": "月亮", "quickdraw": "moon"},
    {"text": "蚊子", "quickdraw": "mosquito"},
    {"text": "摩托车", "quickdraw": "motorbike"},
    {"text": "老鼠", "quickdraw": "mouse"},
    {"text": "嘴巴", "quickdraw": "mouth"},
    {"text": "小胡子", "quickdraw": "moustache"},
    {"text": "马克杯", "quickdraw": "mug"},
    {"text": "钉子", "quickdraw": "nail"},
    {"text": "项链", "quickdraw": "necklace"},
    {"text": "鼻子", "quickdraw": "nose"},
    {"text": "海洋", "quickdraw": "ocean"},
    {"text": "八边形", "quickdraw": "octagon"},
    {"text": "洋葱", "quickdraw": "onion"},
    {"text": "烤箱", "quickdraw": "oven"},
    {"text": "画笔", "quickdraw": "paintbrush"},
    {"text": "油漆桶", "quickdraw": "paint can"},
    {"text": "棕榈树", "quickdraw": "palm tree"},
    {"text": "裤子", "quickdraw": "pants"},
    {"text": "回形针", "quickdraw": "paper clip"},
    {"text": "降落伞", "quickdraw": "parachute"},
    {"text": "梨", "quickdraw": "pear"},
    {"text": "豌豆", "quickdraw": "peas"},
    {"text": "铅笔", "quickdraw": "pencil"},
    {"text": "皮卡车", "quickdraw": "pickup truck"},
    {"text": "相框", "quickdraw": "picture frame"},
    {"text": "枕头", "quickdraw": "pillow"},
    {"text": "钳子", "quickdraw": "pliers"},
    {"text": "警车", "quickdraw": "police car"},
    {"text": "池塘", "quickdraw": "pond"},
    {"text": "游泳池", "quickdraw": "pool"},
    {"text": "冰棍", "quickdraw": "popsicle"},
    {"text": "明信片", "quickdraw": "postcard"},
    {"text": "土豆", "quickdraw": "potato"},
    {"text": "插座", "quickdraw": "power outlet"},
    {"text": "手提包", "quickdraw": "purse"},
    {"text": "浣熊", "quickdraw": "raccoon"},
    {"text": "收音机", "quickdraw": "radio"},
    {"text": "雨", "quickdraw": "rain"},
    {"text": "耙子", "quickdraw": "rake"},
    {"text": "遥控器", "quickdraw": "remote control"},
    {"text": "犀牛", "quickdraw": "rhinoceros"},
    {"text": "步枪", "quickdraw": "rifle"},
    {"text": "河流", "quickdraw": "river"},
    {"text": "过山车", "quickdraw": "roller coaster"},
    {"text": "轮滑鞋", "quickdraw": "rollerskates"},
    {"text": "三明治", "quickdraw": "sandwich"},
    {"text": "锯子", "quickdraw": "saw"},
    {"text": "萨克斯", "quickdraw": "saxophone"},
    {"text": "校车", "quickdraw": "school bus"},
    {"text": "蝎子", "quickdraw": "scorpion"},
    {"text": "螺丝刀", "quickdraw": "screwdriver"},
    {"text": "海龟", "quickdraw": "sea turtle"},
    {"text": "跷跷板", "quickdraw": "see saw"},
    {"text": "鞋子", "quickdraw": "shoe"},
    {"text": "短裤", "quickdraw": "shorts"},
    {"text": "铲子", "quickdraw": "shovel"},
    {"text": "水槽", "quickdraw": "sink"},
    {"text": "滑板", "quickdraw": "skateboard"},
    {"text": "骷髅", "quickdraw": "skull"},
    {"text": "摩天大楼", "quickdraw": "skyscraper"},
    {"text": "睡袋", "quickdraw": "sleeping bag"},
    {"text": "笑脸", "quickdraw": "smiley face"},
    {"text": "蜗牛", "quickdraw": "snail"},
    {"text": "蛇", "quickdraw": "snake"},
    {"text": "潜水呼吸管", "quickdraw": "snorkel"},
    {"text": "雪花", "quickdraw": "snowflake"},
    {"text": "足球", "quickdraw": "soccer ball"},
    {"text": "袜子", "quickdraw": "sock"},
    {"text": "快艇", "quickdraw": "speedboat"},
    {"text": "蜘蛛", "quickdraw": "spider"},
    {"text": "勺子", "quickdraw": "spoon"},
    {"text": "电子表格", "quickdraw": "spreadsheet"},
    {"text": "正方形", "quickdraw": "square"},
    {"text": "波浪线", "quickdraw": "squiggle"},
    {"text": "松鼠", "quickdraw": "squirrel"},
    {"text": "楼梯", "quickdraw": "staircase"},
    {"text": "星星", "quickdraw": "star"},
    {"text": "牛排", "quickdraw": "steak"},
    {"text": "音响", "quickdraw": "stereo"},
    {"text": "听诊器", "quickdraw": "stethoscope"},
    {"text": "缝线", "quickdraw": "stitches"},
    {"text": "停止标志", "quickdraw": "stop sign"},
    {"text": "炉子", "quickdraw": "stove"},
    {"text": "路灯", "quickdraw": "streetlight"},
    {"text": "豆角", "quickdraw": "string bean"},
    {"text": "潜水艇", "quickdraw": "submarine"},
    {"text": "行李箱", "quickdraw": "suitcase"},
    {"text": "天鹅", "quickdraw": "swan"},
    {"text": "毛衣", "quickdraw": "sweater"},
    {"text": "秋千", "quickdraw": "swing set"},
    {"text": "冰球", "quickdraw": "hockey puck"},
    {"text": "灯笼", "quickdraw": "lantern"},
    {"text": "打火机", "quickdraw": "lighter"},
    {"text": "护照", "quickdraw": "passport"},
    {"text": "花生", "quickdraw": "peanut"},
    {"text": "台阶", "quickdraw": "stairs"},
    {"text": "剑", "quickdraw": "sword"},
    {"text": "注射器", "quickdraw": "syringe"},
    {"text": "T恤", "quickdraw": "t-shirt"},
    {"text": "茶壶", "quickdraw": "teapot"},
    {"text": "泰迪熊", "quickdraw": "teddy-bear"},
    {"text": "电话", "quickdraw": "telephone"},
    {"text": "电视", "quickdraw": "television"},
    {"text": "网球拍", "quickdraw": "tennis racquet"},
    {"text": "帐篷", "quickdraw": "tent"},
    {"text": "埃菲尔铁塔", "quickdraw": "The Eiffel Tower"},
    {"text": "中国长城", "quickdraw": "The Great Wall of China"},
    {"text": "蒙娜丽莎", "quickdraw": "The Mona Lisa"},
    {"text": "老虎", "quickdraw": "tiger"},
    {"text": "烤面包机", "quickdraw": "toaster"},
    {"text": "脚趾", "quickdraw": "toe"},
    {"text": "马桶", "quickdraw": "toilet"},
    {"text": "牙齿", "quickdraw": "tooth"},
    {"text": "牙刷", "quickdraw": "toothbrush"},
    {"text": "牙膏", "quickdraw": "toothpaste"},
    {"text": "龙卷风", "quickdraw": "tornado"},
    {"text": "拖拉机", "quickdraw": "tractor"},
    {"text": "红绿灯", "quickdraw": "traffic light"},
    {"text": "三角形", "quickdraw": "triangle"},
    {"text": "长号", "quickdraw": "trombone"},
    {"text": "卡车", "quickdraw": "truck"},
    {"text": "小号", "quickdraw": "trumpet"},
    {"text": "内衣", "quickdraw": "underwear"},
    {"text": "面包车", "quickdraw": "van"},
    {"text": "花瓶", "quickdraw": "vase"},
    {"text": "小提琴", "quickdraw": "violin"},
    {"text": "洗衣机", "quickdraw": "washing machine"},
    {"text": "西瓜", "quickdraw": "watermelon"},
    {"text": "水上滑梯", "quickdraw": "waterslide"},
    {"text": "车轮", "quickdraw": "wheel"},
    {"text": "风车", "quickdraw": "windmill"},
    {"text": "葡萄酒瓶", "quickdraw": "wine bottle"},
    {"text": "葡萄酒杯", "quickdraw": "wine glass"},
    {"text": "手表", "quickdraw": "wristwatch"},
    {"text": "瑜伽", "quickdraw": "yoga"},
    {"text": "之字形", "quickdraw": "zigzag"},
]

DEFAULT_PROMPTS_BY_LANGUAGE = {
    "en": DEFAULT_PROMPTS_EN,
    "zh": DEFAULT_PROMPTS_ZH,
}

ENGLISH_ALIAS_OVERRIDES = {
    entry["text"]: entry["quickdraw"]
    for entry in DEFAULT_PROMPTS_EN
    if entry.get("quickdraw") and entry["quickdraw"] != entry["text"]
}

CHINESE_TO_QUICKDRAW = {
    entry["text"]: entry["quickdraw"]
    for entry in DEFAULT_PROMPTS_ZH
    if entry.get("quickdraw")
}
