"""Mechanism data for the Spirit Island introductory rules.

Numeric rules, names, and original Chinese summaries; no official artwork.
Sources and verification notes: designs/spirit_island_sources.md.
Track index zero is initially uncovered; every added Presence uncovers one slot.
"""

from typing import Dict

BOARDS: Dict = {'A': {'name': '岛板 A',
       'lands': [{'id': 1,
                  'terrain': 'mountain',
                  'coastal': True,
                  'adjacent': [2, 4, 5, 6],
                  'dahan': 0,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0},
                 {'id': 2,
                  'terrain': 'wetland',
                  'coastal': True,
                  'adjacent': [1, 3, 4],
                  'dahan': 1,
                  'explorer': 0,
                  'town': 0,
                  'city': 1,
                  'blight': 0},
                 {'id': 3,
                  'terrain': 'jungle',
                  'coastal': True,
                  'adjacent': [2, 4],
                  'dahan': 2,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0},
                 {'id': 4,
                  'terrain': 'sand',
                  'coastal': False,
                  'adjacent': [1, 2, 3, 5],
                  'dahan': 0,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 1},
                 {'id': 5,
                  'terrain': 'wetland',
                  'coastal': False,
                  'adjacent': [1, 4, 6, 7, 8],
                  'dahan': 0,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0},
                 {'id': 6,
                  'terrain': 'mountain',
                  'coastal': False,
                  'adjacent': [1, 5, 8],
                  'dahan': 1,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0},
                 {'id': 7,
                  'terrain': 'sand',
                  'coastal': False,
                  'adjacent': [5, 8],
                  'dahan': 2,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0},
                 {'id': 8,
                  'terrain': 'jungle',
                  'coastal': False,
                  'adjacent': [5, 6, 7],
                  'dahan': 0,
                  'explorer': 0,
                  'town': 1,
                  'city': 0,
                  'blight': 0}]},
 'B': {'name': '岛板 B',
       'lands': [{'id': 1,
                  'terrain': 'wetland',
                  'coastal': True,
                  'adjacent': [2, 4, 5, 6],
                  'dahan': 1,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0},
                 {'id': 2,
                  'terrain': 'mountain',
                  'coastal': True,
                  'adjacent': [1, 3, 4],
                  'dahan': 0,
                  'explorer': 0,
                  'town': 0,
                  'city': 1,
                  'blight': 0},
                 {'id': 3,
                  'terrain': 'sand',
                  'coastal': True,
                  'adjacent': [2, 4],
                  'dahan': 2,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0},
                 {'id': 4,
                  'terrain': 'jungle',
                  'coastal': False,
                  'adjacent': [1, 2, 3, 5, 7],
                  'dahan': 0,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 1},
                 {'id': 5,
                  'terrain': 'sand',
                  'coastal': False,
                  'adjacent': [1, 4, 6, 7],
                  'dahan': 0,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0},
                 {'id': 6,
                  'terrain': 'wetland',
                  'coastal': False,
                  'adjacent': [1, 5, 7, 8],
                  'dahan': 0,
                  'explorer': 0,
                  'town': 1,
                  'city': 0,
                  'blight': 0},
                 {'id': 7,
                  'terrain': 'mountain',
                  'coastal': False,
                  'adjacent': [4, 5, 6, 8],
                  'dahan': 1,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0},
                 {'id': 8,
                  'terrain': 'jungle',
                  'coastal': False,
                  'adjacent': [6, 7],
                  'dahan': 2,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0}]},
 'C': {'name': '岛板 C',
       'lands': [{'id': 1,
                  'terrain': 'jungle',
                  'coastal': True,
                  'adjacent': [2, 5, 6],
                  'dahan': 1,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0},
                 {'id': 2,
                  'terrain': 'sand',
                  'coastal': True,
                  'adjacent': [1, 3, 4, 5],
                  'dahan': 0,
                  'explorer': 0,
                  'town': 0,
                  'city': 1,
                  'blight': 0},
                 {'id': 3,
                  'terrain': 'mountain',
                  'coastal': True,
                  'adjacent': [2, 4],
                  'dahan': 2,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0},
                 {'id': 4,
                  'terrain': 'jungle',
                  'coastal': False,
                  'adjacent': [2, 3, 5, 7],
                  'dahan': 0,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0},
                 {'id': 5,
                  'terrain': 'wetland',
                  'coastal': False,
                  'adjacent': [1, 2, 4, 6, 7],
                  'dahan': 2,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 1},
                 {'id': 6,
                  'terrain': 'sand',
                  'coastal': False,
                  'adjacent': [1, 5, 7, 8],
                  'dahan': 1,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0},
                 {'id': 7,
                  'terrain': 'mountain',
                  'coastal': False,
                  'adjacent': [4, 5, 6, 8],
                  'dahan': 0,
                  'explorer': 0,
                  'town': 1,
                  'city': 0,
                  'blight': 0},
                 {'id': 8,
                  'terrain': 'wetland',
                  'coastal': False,
                  'adjacent': [6, 7],
                  'dahan': 0,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0}]},
 'D': {'name': '岛板 D',
       'lands': [{'id': 1,
                  'terrain': 'wetland',
                  'coastal': True,
                  'adjacent': [2, 5, 7, 8],
                  'dahan': 2,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0},
                 {'id': 2,
                  'terrain': 'jungle',
                  'coastal': True,
                  'adjacent': [1, 3, 4, 5],
                  'dahan': 1,
                  'explorer': 0,
                  'town': 0,
                  'city': 1,
                  'blight': 0},
                 {'id': 3,
                  'terrain': 'wetland',
                  'coastal': True,
                  'adjacent': [2, 4],
                  'dahan': 0,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0},
                 {'id': 4,
                  'terrain': 'sand',
                  'coastal': False,
                  'adjacent': [2, 3, 5, 6],
                  'dahan': 0,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0},
                 {'id': 5,
                  'terrain': 'mountain',
                  'coastal': False,
                  'adjacent': [1, 2, 4, 6, 7],
                  'dahan': 1,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 1},
                 {'id': 6,
                  'terrain': 'jungle',
                  'coastal': False,
                  'adjacent': [4, 5, 7],
                  'dahan': 0,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0},
                 {'id': 7,
                  'terrain': 'sand',
                  'coastal': False,
                  'adjacent': [1, 5, 6, 8],
                  'dahan': 2,
                  'explorer': 0,
                  'town': 1,
                  'city': 0,
                  'blight': 0},
                 {'id': 8,
                  'terrain': 'mountain',
                  'coastal': False,
                  'adjacent': [1, 7],
                  'dahan': 0,
                  'explorer': 0,
                  'town': 0,
                  'city': 0,
                  'blight': 0}]}}

BOARD_LAYOUTS: Dict = {1: ['A'], 2: ['A', 'C'], 3: ['B', 'C', 'D'], 4: ['A', 'B', 'C', 'D']}

CROSS_BOARD_EDGES: Dict = {1: [],
 2: [('A3', 'C4'), ('A4', 'C4'), ('A4', 'C3'), ('A5', 'C3'), ('A7', 'C3')],
 3: [('B8', 'C3'),
     ('B7', 'C3'),
     ('B7', 'C4'),
     ('C4', 'D6'),
     ('C7', 'D6'),
     ('C7', 'D7'),
     ('C8', 'D7'),
     ('C8', 'D3'),
     ('B7', 'D6'),
     ('B4', 'D6'),
     ('B4', 'D7'),
     ('B3', 'D7'),
     ('B3', 'D8')],
 4: [('A8', 'D6'),
     ('A8', 'D7'),
     ('A7', 'D7'),
     ('A7', 'D8'),
     ('A3', 'B1'),
     ('A3', 'B6'),
     ('A4', 'B6'),
     ('A4', 'B8'),
     ('A5', 'B8'),
     ('A7', 'B8'),
     ('D8', 'C4'),
     ('D1', 'C4'),
     ('D1', 'C3'),
     ('B8', 'C4'),
     ('B8', 'C7'),
     ('B7', 'C7'),
     ('B7', 'C8'),
     ('A7', 'C4'),
     ('B8', 'D8')]}

SPIRITS: Dict = {'lightning': {'name': '雷霆迅击',
               'name_en': "Lightning's Swift Strike",
               'complexity': 'low',
               'energy_track': [1, 1, 2, 2, 3, 4, 4, 5],
               'plays_track': [2, 3, 4, 5, 6],
               'reclaim_one_at': None,
               'growth': [{'id': '1',
                           'name': '收回弃牌；学习力量；获得 1 能量',
                           'reclaim': True,
                           'gain_power': True,
                           'energy': 1,
                           'presence_ranges': []},
                          {'id': '2',
                           'name': '放置存在 距离 2 / 距离 0',
                           'reclaim': False,
                           'gain_power': False,
                           'energy': 0,
                           'presence_ranges': [2, 0]},
                          {'id': '3',
                           'name': '放置存在 距离 1；获得 3 能量',
                           'reclaim': False,
                           'gain_power': False,
                           'energy': 3,
                           'presence_ranges': [1]}],
               'setup': [{'terrain': 'sand', 'highest': True, 'count': 2}],
               'starting_powers': ['raging_storm',
                                   'shatter_homesteads',
                                   'lightnings_boon',
                                   'harbingers_of_the_lightning'],
               'progression': ['delusions_of_danger',
                               'call_to_bloodshed',
                               'powerstorm',
                               'purifying_flame',
                               'pillar_of_living_flame',
                               'entrancing_apparitions',
                               'call_to_isolation'],
               'special': '每个风元素允许你把 1 个慢速力量作为快速力量使用（包括天赋）。',
               'innate': {'id': 'thundering_destruction',
                          'name': '雷鸣毁灭',
                          'name_en': 'Thundering Destruction',
                          'description': '摧毁 1 村镇。 上述摧毁可改为 1 城市。 额外摧毁 1 村镇或城市。 再额外摧毁 1 村镇或城市。',
                          'speed': 'slow',
                          'range': 1,
                          'target': 'land',
                          'sacred_site': True,
                          'thresholds': [{'elements': {'fire': 3, 'air': 2}, 'description': '摧毁 1 村镇。'},
                                         {'elements': {'fire': 4, 'air': 3}, 'description': '上述摧毁可改为 1 城市。'},
                                         {'elements': {'fire': 5, 'air': 4, 'water': 1},
                                          'description': '额外摧毁 1 村镇或城市。'},
                                         {'elements': {'fire': 5, 'air': 5, 'water': 2},
                                          'description': '再额外摧毁 1 村镇或城市。'}]}},
 'river': {'name': '阳光下的河流',
           'name_en': 'River Surges in Sunlight',
           'complexity': 'low',
           'energy_track': [1, 2, 2, 3, 4, 4, 5],
           'plays_track': [1, 2, 2, 3, 3, 4, 5],
           'reclaim_one_at': 4,
           'growth': [{'id': '1',
                       'name': '收回弃牌；学习力量；获得 1 能量',
                       'reclaim': True,
                       'gain_power': True,
                       'energy': 1,
                       'presence_ranges': []},
                      {'id': '2',
                       'name': '放置存在 距离 1 / 距离 1',
                       'reclaim': False,
                       'gain_power': False,
                       'energy': 0,
                       'presence_ranges': [1, 1]},
                      {'id': '3',
                       'name': '学习力量；放置存在 距离 2',
                       'reclaim': False,
                       'gain_power': True,
                       'energy': 0,
                       'presence_ranges': [2]}],
           'setup': [{'terrain': 'wetland', 'highest': True, 'count': 1}],
           'starting_powers': ['boon_of_vigor', 'rivers_bounty', 'wash_away', 'flash_floods'],
           'progression': ['uncanny_melting',
                           'natures_resilience',
                           'pull_beneath_the_hungry_earth',
                           'accelerated_rot',
                           'song_of_sanctity',
                           'tsunami',
                           'encompassing_ward'],
           'special': '你在湿地的存在视为圣地，只有 1 枚存在也成立。',
           'innate': {'id': 'massive_flooding',
                      'name': '滔天洪水',
                      'name_en': 'Massive Flooding',
                      'description': '推离 1 探索者或村镇。 改为：造成 2 伤害，推离至多 3 探索者或村镇。 改为：每个入侵者各受 2 伤害。',
                      'speed': 'slow',
                      'range': 1,
                      'target': 'land',
                      'sacred_site': True,
                      'thresholds': [{'elements': {'sun': 1, 'water': 2}, 'description': '推离 1 探索者或村镇。'},
                                     {'elements': {'sun': 2, 'water': 3},
                                      'description': '改为：造成 2 伤害，推离至多 3 探索者或村镇。'},
                                     {'elements': {'sun': 3, 'water': 4, 'earth': 1},
                                      'description': '改为：每个入侵者各受 2 伤害。'}]}},
 'earth': {'name': '大地磐岩',
           'name_en': 'Vital Strength of the Earth',
           'complexity': 'low',
           'energy_track': [2, 3, 4, 6, 7, 8],
           'plays_track': [1, 1, 2, 2, 3, 4],
           'reclaim_one_at': None,
           'growth': [{'id': '1',
                       'name': '收回弃牌；放置存在 距离 2',
                       'reclaim': True,
                       'gain_power': False,
                       'energy': 0,
                       'presence_ranges': [2]},
                      {'id': '2',
                       'name': '学习力量；放置存在 距离 0',
                       'reclaim': False,
                       'gain_power': True,
                       'energy': 0,
                       'presence_ranges': [0]},
                      {'id': '3',
                       'name': '放置存在 距离 1；获得 2 能量',
                       'reclaim': False,
                       'gain_power': False,
                       'energy': 2,
                       'presence_ranges': [1]}],
           'setup': [{'terrain': 'mountain', 'highest': True, 'count': 2},
                     {'terrain': 'jungle', 'highest': True, 'count': 1}],
           'starting_powers': ['a_year_of_perfect_stillness',
                               'draw_of_the_fruitful_earth',
                               'guard_the_healing_land',
                               'rituals_of_destruction'],
           'progression': ['rouse_the_trees_and_stones',
                           'call_to_migrate',
                           'poisoned_land',
                           'devouring_ants',
                           'vigor_of_the_breaking_dawn',
                           'voracious_growth',
                           'savage_mawbeasts'],
           'special': '你的每块圣地在本轮提供 3 防御。',
           'innate': {'id': 'gift_of_strength',
                      'name': '力量赐福',
                      'name_en': 'Gift Of Strength',
                      'description': '目标本轮可免费重复 1 张费用不超过 1 的力量牌。 费用上限改为 3。 费用上限改为 6。',
                      'speed': 'fast',
                      'range': None,
                      'target': 'spirit',
                      'sacred_site': False,
                      'thresholds': [{'elements': {'sun': 1, 'earth': 2, 'plant': 2},
                                      'description': '目标本轮可免费重复 1 张费用不超过 1 的力量牌。'},
                                     {'elements': {'sun': 2, 'earth': 3, 'plant': 2},
                                      'description': '费用上限改为 3。'},
                                     {'elements': {'sun': 2, 'earth': 4, 'plant': 3},
                                      'description': '费用上限改为 6。'}]}},
 'shadows': {'name': '如焰暗影',
             'name_en': 'Shadows Flicker Like Flame',
             'complexity': 'low',
             'energy_track': [0, 1, 3, 4, 5, 6],
             'plays_track': [1, 2, 3, 3, 4, 5],
             'reclaim_one_at': None,
             'growth': [{'id': '1',
                         'name': '收回弃牌；学习力量',
                         'reclaim': True,
                         'gain_power': True,
                         'energy': 0,
                         'presence_ranges': []},
                        {'id': '2',
                         'name': '学习力量；放置存在 距离 1',
                         'reclaim': False,
                         'gain_power': True,
                         'energy': 0,
                         'presence_ranges': [1]},
                        {'id': '3',
                         'name': '放置存在 距离 3；获得 3 能量',
                         'reclaim': False,
                         'gain_power': False,
                         'energy': 3,
                         'presence_ranges': [3]}],
             'setup': [{'terrain': 'jungle', 'highest': True, 'count': 2}, {'land_number': 5, 'count': 1}],
             'starting_powers': ['concealing_shadows',
                                 'crops_wither_and_fade',
                                 'favors_called_due',
                                 'mantle_of_dread'],
             'progression': ['dark_and_tangled_woods',
                             'shadows_of_the_burning_forest',
                             'the_jungle_hungers',
                             'land_of_haunts_and_embers',
                             'terrifying_nightmares',
                             'call_of_the_dahan_ways',
                             'visions_of_fiery_doom'],
             'special': '使用力量时，可支付 1 能量，无视距离选择有达汉的土地；其他目标限制仍适用。',
             'innate': {'id': 'darkness_swallows_the_unwary',
                        'name': '暗夜吞噬疏忽者',
                        'name_en': 'Darkness Swallows The Unwary',
                        'description': '聚集 1 探索者。 摧毁至多 2 探索者，每个额外产生 1 恐惧。 再造成 3 伤害；本次伤害每摧毁 1 入侵者额外产生 1 恐惧。',
                        'speed': 'fast',
                        'range': 1,
                        'target': 'land',
                        'sacred_site': True,
                        'thresholds': [{'elements': {'moon': 2, 'fire': 1}, 'description': '聚集 1 探索者。'},
                                       {'elements': {'moon': 3, 'fire': 2},
                                        'description': '摧毁至多 2 探索者，每个额外产生 1 恐惧。'},
                                       {'elements': {'moon': 4, 'fire': 3, 'air': 2},
                                        'description': '再造成 3 伤害；本次伤害每摧毁 1 入侵者额外产生 1 恐惧。'}]}}}

POWERS: Dict = {'delusions_of_danger': {'name': '危机幻象',
                         'name_en': 'Delusions of Danger',
                         'cost': 1,
                         'speed': 'fast',
                         'range': 1,
                         'target': 'land',
                         'target_filter': {},
                         'sacred_site': False,
                         'elements': ['sun', 'moon', 'air'],
                         'type': 'minor',
                         'description': '二选一：推离 1 探索者；或产生 2 恐惧。',
                         'threshold': {}},
 'call_to_bloodshed': {'name': '浴血召唤',
                       'name_en': 'Call to Bloodshed',
                       'cost': 1,
                       'speed': 'slow',
                       'range': 1,
                       'target': 'land',
                       'target_filter': {'dahan': True},
                       'sacred_site': False,
                       'elements': ['sun', 'fire', 'animal'],
                       'type': 'minor',
                       'description': '二选一：每个达汉造成 1 伤害；或聚集至多 3 达汉。',
                       'threshold': {}},
 'powerstorm': {'name': '力量风暴',
                'name_en': 'Powerstorm',
                'cost': 3,
                'speed': 'fast',
                'range': None,
                'target': 'spirit',
                'target_filter': {},
                'sacred_site': False,
                'elements': ['sun', 'fire', 'air'],
                'type': 'major',
                'description': '目标精灵获得 3 能量，本轮可付费重复使用 1 张力量牌；达到元素门槛后，可再重复 2 张不同力量牌。',
                'threshold': {'sun': 2, 'fire': 2, 'air': 3}},
 'purifying_flame': {'name': '净化火焰',
                     'name_en': 'Purifying Flame',
                     'cost': 1,
                     'speed': 'slow',
                     'range': 1,
                     'target': 'land',
                     'target_filter': {},
                     'sacred_site': True,
                     'elements': ['sun', 'fire', 'air', 'plant'],
                     'type': 'minor',
                     'description': '每个荒芜造成 1 伤害；山地或沙地可改为移除 1 荒芜。',
                     'threshold': {}},
 'pillar_of_living_flame': {'name': '炽焰巨柱',
                            'name_en': 'Pillar of Living Flame',
                            'cost': 5,
                            'speed': 'slow',
                            'range': 2,
                            'target': 'land',
                            'target_filter': {},
                            'sacred_site': True,
                            'elements': ['fire'],
                            'type': 'major',
                            'description': '产生 3 恐惧、造成 5 伤害；丛林或湿地增加 1 荒芜。门槛额外产生 2 恐惧、造成 5 伤害。',
                            'threshold': {'fire': 4}},
 'entrancing_apparitions': {'name': '迷魂幻影',
                            'name_en': 'Entrancing Apparitions',
                            'cost': 1,
                            'speed': 'fast',
                            'range': 1,
                            'target': 'land',
                            'target_filter': {},
                            'sacred_site': False,
                            'elements': ['moon', 'air', 'water'],
                            'type': 'minor',
                            'description': '提供 2 防御；目标地没有入侵者时可聚集至多 2 探索者。',
                            'threshold': {}},
 'call_to_isolation': {'name': '离群召唤',
                       'name_en': 'Call to Isolation',
                       'cost': 0,
                       'speed': 'fast',
                       'range': 1,
                       'target': 'land',
                       'target_filter': {'dahan': True},
                       'sacred_site': False,
                       'elements': ['sun', 'air', 'animal'],
                       'type': 'minor',
                       'description': '二选一：每个达汉可推离 1 探索者或村镇；或推离 1 达汉。',
                       'threshold': {}},
 'uncanny_melting': {'name': '诡异消融',
                     'name_en': 'Uncanny Melting',
                     'cost': 1,
                     'speed': 'slow',
                     'range': 1,
                     'target': 'land',
                     'target_filter': {},
                     'sacred_site': True,
                     'elements': ['sun', 'moon', 'water'],
                     'type': 'minor',
                     'description': '有入侵者时产生 1 恐惧；沙地或湿地移除 1 荒芜。',
                     'threshold': {}},
 'pull_beneath_the_hungry_earth': {'name': '饥渴大地',
                                   'name_en': 'Pull Beneath the Hungry Earth',
                                   'cost': 1,
                                   'speed': 'slow',
                                   'range': 1,
                                   'target': 'land',
                                   'target_filter': {},
                                   'sacred_site': False,
                                   'elements': ['moon', 'water', 'earth'],
                                   'type': 'minor',
                                   'description': '有自己存在时产生 1 恐惧、造成 1 伤害；沙地或湿地再造成 1 伤害。',
                                   'threshold': {}},
 'accelerated_rot': {'name': '加速腐朽',
                     'name_en': 'Accelerated Rot',
                     'cost': 4,
                     'speed': 'slow',
                     'range': 2,
                     'target': 'land',
                     'target_filter': {'terrain': ['jungle', 'wetland']},
                     'sacred_site': False,
                     'elements': ['sun', 'water', 'plant'],
                     'type': 'major',
                     'description': '产生 2 恐惧、造成 4 伤害；门槛额外造成 5 伤害，并移除 1 荒芜。',
                     'threshold': {'sun': 3, 'water': 2, 'plant': 3}},
 'song_of_sanctity': {'name': '圣洁之歌',
                      'name_en': 'Song of Sanctity',
                      'cost': 1,
                      'speed': 'slow',
                      'range': 1,
                      'target': 'land',
                      'target_filter': {'terrain': ['mountain', 'jungle']},
                      'sacred_site': False,
                      'elements': ['sun', 'water', 'plant'],
                      'type': 'minor',
                      'description': '有探索者则推离全部探索者；否则移除 1 荒芜。',
                      'threshold': {}},
 'tsunami': {'name': '海啸',
             'name_en': 'Tsunami',
             'cost': 6,
             'speed': 'slow',
             'range': 2,
             'target': 'land',
             'target_filter': {'coastal': True},
             'sacred_site': True,
             'elements': ['water', 'earth'],
             'type': 'major',
             'description': '产生 2 恐惧、造成 8 伤害、摧毁 2 达汉；门槛影响同板其他沿海地：各产生 1 恐惧、造成 4 伤害、摧毁 1 达汉。',
             'threshold': {'water': 3, 'earth': 2}},
 'encompassing_ward': {'name': '周全守护',
                       'name_en': 'Encompassing Ward',
                       'cost': 1,
                       'speed': 'fast',
                       'range': None,
                       'target': 'spirit',
                       'target_filter': {},
                       'sacred_site': False,
                       'elements': ['sun', 'water', 'earth'],
                       'type': 'minor',
                       'description': '目标精灵本轮在其每块有存在的土地提供 2 防御。',
                       'threshold': {}},
 'a_year_of_perfect_stillness': {'name': '万籁俱寂之年',
                                 'name_en': 'A Year of Perfect Stillness',
                                 'cost': 3,
                                 'speed': 'fast',
                                 'range': 1,
                                 'target': 'land',
                                 'target_filter': {},
                                 'sacred_site': False,
                                 'elements': ['sun', 'earth'],
                                 'type': 'unique',
                                 'description': '目标地本轮跳过所有入侵者行动。',
                                 'threshold': {},
                                 'spirit': 'earth'},
 'draw_of_the_fruitful_earth': {'name': '沃土的召唤',
                                'name_en': 'Draw of the Fruitful Earth',
                                'cost': 1,
                                'speed': 'slow',
                                'range': 1,
                                'target': 'land',
                                'target_filter': {},
                                'sacred_site': False,
                                'elements': ['earth', 'plant', 'animal'],
                                'type': 'unique',
                                'description': '聚集至多 2 探索者，再聚集至多 2 达汉。',
                                'threshold': {},
                                'spirit': 'earth'},
 'guard_the_healing_land': {'name': '守护复苏之地',
                            'name_en': 'Guard the Healing Land',
                            'cost': 3,
                            'speed': 'fast',
                            'range': 1,
                            'target': 'land',
                            'target_filter': {},
                            'sacred_site': True,
                            'elements': ['water', 'earth', 'plant'],
                            'type': 'unique',
                            'description': '移除 1 荒芜，并在本轮提供 4 防御。',
                            'threshold': {},
                            'spirit': 'earth'},
 'rituals_of_destruction': {'name': '毁灭仪式',
                            'name_en': 'Rituals of Destruction',
                            'cost': 3,
                            'speed': 'slow',
                            'range': 1,
                            'target': 'land',
                            'target_filter': {'dahan': True},
                            'sacred_site': True,
                            'elements': ['sun', 'moon', 'fire', 'earth', 'plant'],
                            'type': 'unique',
                            'description': '造成 2 伤害；若至少有 3 达汉，额外造成 3 伤害并产生 2 恐惧。',
                            'threshold': {},
                            'spirit': 'earth'},
 'rouse_the_trees_and_stones': {'name': '唤醒树石',
                                'name_en': 'Rouse the Trees and Stones',
                                'cost': 1,
                                'speed': 'slow',
                                'range': 1,
                                'target': 'land',
                                'target_filter': {'no_blight': True},
                                'sacred_site': True,
                                'elements': ['fire', 'earth', 'plant'],
                                'type': 'minor',
                                'description': '造成 2 伤害，随后可推离 1 探索者。',
                                'threshold': {}},
 'call_to_migrate': {'name': '迁徙召唤',
                     'name_en': 'Call to Migrate',
                     'cost': 1,
                     'speed': 'slow',
                     'range': 1,
                     'target': 'land',
                     'target_filter': {},
                     'sacred_site': False,
                     'elements': ['fire', 'air', 'animal'],
                     'type': 'minor',
                     'description': '聚集至多 3 达汉，再推离至多 3 达汉。',
                     'threshold': {}},
 'poisoned_land': {'name': '毒化土地',
                   'name_en': 'Poisoned Land',
                   'cost': 3,
                   'speed': 'slow',
                   'range': 1,
                   'target': 'land',
                   'target_filter': {},
                   'sacred_site': False,
                   'elements': ['earth', 'plant', 'animal'],
                   'type': 'major',
                   'description': '产生 1 恐惧、造成 7 伤害，增加 1 荒芜并摧毁全部达汉；门槛按现有每个荒芜再产生 1 恐惧、造成 4 伤害。',
                   'threshold': {'earth': 3, 'plant': 2, 'animal': 2}},
 'devouring_ants': {'name': '吞噬蚁群',
                    'name_en': 'Devouring Ants',
                    'cost': 1,
                    'speed': 'slow',
                    'range': 1,
                    'target': 'land',
                    'target_filter': {},
                    'sacred_site': True,
                    'elements': ['sun', 'earth', 'animal'],
                    'type': 'minor',
                    'description': '产生 1 恐惧、造成 1 伤害并摧毁 1 达汉；丛林或沙地额外造成 1 伤害。',
                    'threshold': {}},
 'vigor_of_the_breaking_dawn': {'name': '破晓活力',
                                'name_en': 'Vigor of the Breaking Dawn',
                                'cost': 3,
                                'speed': 'fast',
                                'range': 2,
                                'target': 'land',
                                'target_filter': {'dahan': True},
                                'sacred_site': False,
                                'elements': ['sun', 'animal'],
                                'type': 'major',
                                'description': '每个达汉造成 2 伤害；门槛可再推离至多 2 达汉，其抵达土地按当地每个达汉造成 2 伤害。',
                                'threshold': {'sun': 3, 'animal': 2}},
 'voracious_growth': {'name': '贪婪生长',
                      'name_en': 'Voracious Growth',
                      'cost': 1,
                      'speed': 'slow',
                      'range': 1,
                      'target': 'land',
                      'target_filter': {'terrain': ['jungle', 'wetland']},
                      'sacred_site': True,
                      'elements': ['water', 'plant'],
                      'type': 'minor',
                      'description': '二选一：造成 2 伤害；或移除 1 荒芜。',
                      'threshold': {}},
 'savage_mawbeasts': {'name': '凶猛巨颚兽',
                      'name_en': 'Savage Mawbeasts',
                      'cost': 0,
                      'speed': 'slow',
                      'range': 1,
                      'target': 'land',
                      'target_filter': {},
                      'sacred_site': True,
                      'elements': ['fire', 'animal'],
                      'type': 'minor',
                      'description': '丛林或湿地产生 1 恐惧、造成 1 伤害；达到 3 兽门槛额外造成 1 伤害。',
                      'threshold': {'animal': 3}},
 'concealing_shadows': {'name': '隐匿暗影',
                        'name_en': 'Concealing Shadows',
                        'cost': 0,
                        'speed': 'fast',
                        'range': 0,
                        'target': 'land',
                        'target_filter': {},
                        'sacred_site': False,
                        'elements': ['moon', 'air'],
                        'type': 'unique',
                        'description': '产生 1 恐惧；本轮目标地达汉不受入侵者蹂躏伤害。',
                        'threshold': {},
                        'spirit': 'shadows'},
 'crops_wither_and_fade': {'name': '作物枯萎',
                           'name_en': 'Crops Wither and Fade',
                           'cost': 1,
                           'speed': 'slow',
                           'range': 0,
                           'target': 'land',
                           'target_filter': {},
                           'sacred_site': False,
                           'elements': ['moon', 'fire', 'plant'],
                           'type': 'unique',
                           'description': '产生 2 恐惧；将 1 村镇降为探索者，或将 1 城市降为村镇。',
                           'threshold': {},
                           'spirit': 'shadows'},
 'favors_called_due': {'name': '偿还旧恩',
                       'name_en': 'Favors Called Due',
                       'cost': 1,
                       'speed': 'slow',
                       'range': 1,
                       'target': 'land',
                       'target_filter': {},
                       'sacred_site': False,
                       'elements': ['moon', 'air', 'animal'],
                       'type': 'unique',
                       'description': '聚集至多 4 达汉；随后若入侵者仍在且达汉数多于入侵者，产生 3 恐惧。',
                       'threshold': {},
                       'spirit': 'shadows'},
 'mantle_of_dread': {'name': '恐惧披风',
                     'name_en': 'Mantle of Dread',
                     'cost': 1,
                     'speed': 'slow',
                     'range': None,
                     'target': 'spirit',
                     'target_filter': {},
                     'sacred_site': False,
                     'elements': ['moon', 'fire', 'air'],
                     'type': 'unique',
                     'description': '产生 2 恐惧；目标精灵可从自己有存在的同一土地推离 1 探索者和 1 村镇。',
                     'threshold': {},
                     'spirit': 'shadows'},
 'dark_and_tangled_woods': {'name': '幽暗密林',
                            'name_en': 'Dark and Tangled Woods',
                            'cost': 1,
                            'speed': 'fast',
                            'range': 1,
                            'target': 'land',
                            'target_filter': {},
                            'sacred_site': False,
                            'elements': ['moon', 'earth', 'plant'],
                            'type': 'minor',
                            'description': '产生 2 恐惧；山地或丛林提供 3 防御。',
                            'threshold': {}},
 'shadows_of_the_burning_forest': {'name': '燃林暗影',
                                   'name_en': 'Shadows of the Burning Forest',
                                   'cost': 0,
                                   'speed': 'slow',
                                   'range': 0,
                                   'target': 'land',
                                   'target_filter': {'invaders': True},
                                   'sacred_site': False,
                                   'elements': ['moon', 'fire', 'plant'],
                                   'type': 'minor',
                                   'description': '产生 2 恐惧；山地或丛林可推离 1 探索者和 1 村镇。',
                                   'threshold': {}},
 'the_jungle_hungers': {'name': '丛林饥渴',
                        'name_en': 'The Jungle Hungers',
                        'cost': 3,
                        'speed': 'slow',
                        'range': 1,
                        'target': 'land',
                        'target_filter': {},
                        'sacred_site': False,
                        'elements': ['moon', 'plant'],
                        'type': 'major',
                        'description': '摧毁全部探索者、村镇和达汉；门槛再摧毁 1 城市，并保护达汉免遭本力量摧毁。',
                        'threshold': {'moon': 2, 'plant': 3},
                        'source_terrain': 'jungle'},
 'land_of_haunts_and_embers': {'name': '幽魂余烬之地',
                               'name_en': 'Land of Haunts and Embers',
                               'cost': 0,
                               'speed': 'fast',
                               'range': 2,
                               'target': 'land',
                               'target_filter': {},
                               'sacred_site': False,
                               'elements': ['moon', 'fire', 'air'],
                               'type': 'minor',
                               'description': '产生 2 恐惧并推离至多 2 探索者或村镇；已有荒芜则再执行一次这两项效果；最后增加 1 荒芜。',
                               'threshold': {}},
 'terrifying_nightmares': {'name': '可怖梦魇',
                           'name_en': 'Terrifying Nightmares',
                           'cost': 4,
                           'speed': 'fast',
                           'range': 2,
                           'target': 'land',
                           'target_filter': {},
                           'sacred_site': False,
                           'elements': ['moon', 'air'],
                           'type': 'major',
                           'description': '产生 2 恐惧并推离至多 4 探索者或村镇；达到 4 月门槛额外产生 4 恐惧。',
                           'threshold': {'moon': 4}},
 'call_of_the_dahan_ways': {'name': '达汉之道',
                            'name_en': 'Call of the Dahan Ways',
                            'cost': 1,
                            'speed': 'slow',
                            'range': 1,
                            'target': 'land',
                            'target_filter': {'dahan': True},
                            'sacred_site': False,
                            'elements': ['moon', 'water', 'animal'],
                            'type': 'minor',
                            'description': '将 1 探索者转化为 1 达汉；达到 2 月门槛可改为转化 1 村镇。',
                            'threshold': {'moon': 2}},
 'visions_of_fiery_doom': {'name': '火劫幻视',
                           'name_en': 'Visions of Fiery Doom',
                           'cost': 1,
                           'speed': 'fast',
                           'range': 0,
                           'target': 'land',
                           'target_filter': {},
                           'sacred_site': False,
                           'elements': ['moon', 'fire'],
                           'type': 'minor',
                           'description': '产生 1 恐惧，推离 1 探索者或村镇；达到 2 火门槛再产生 1 恐惧。',
                           'threshold': {'fire': 2}},
 'harbingers_of_the_lightning': {'name': '闪电先兆',
                                 'name_en': 'Harbingers of the Lightning',
                                 'cost': 0,
                                 'speed': 'slow',
                                 'range': 1,
                                 'target': 'land',
                                 'target_filter': {},
                                 'sacred_site': False,
                                 'elements': ['fire', 'air'],
                                 'type': 'unique',
                                 'description': '推离至多 2 达汉；若有达汉进入含村镇或城市的土地，产生 1 恐惧。',
                                 'threshold': {},
                                 'spirit': 'lightning'},
 'lightnings_boon': {'name': '闪电恩泽',
                     'name_en': "Lightning's Boon",
                     'cost': 1,
                     'speed': 'fast',
                     'range': None,
                     'target': 'spirit',
                     'target_filter': {},
                     'sacred_site': False,
                     'elements': ['fire', 'air'],
                     'type': 'unique',
                     'description': '目标精灵本轮可将至多 2 个慢速力量作为快速力量使用。',
                     'threshold': {},
                     'spirit': 'lightning'},
 'shatter_homesteads': {'name': '击碎村落',
                        'name_en': 'Shatter Homesteads',
                        'cost': 2,
                        'speed': 'slow',
                        'range': 2,
                        'target': 'land',
                        'target_filter': {},
                        'sacred_site': True,
                        'elements': ['fire', 'air'],
                        'type': 'unique',
                        'description': '产生 1 恐惧，并摧毁 1 村镇。',
                        'threshold': {},
                        'spirit': 'lightning'},
 'raging_storm': {'name': '狂怒风暴',
                  'name_en': 'Raging Storm',
                  'cost': 3,
                  'speed': 'slow',
                  'range': 1,
                  'target': 'land',
                  'target_filter': {},
                  'sacred_site': False,
                  'elements': ['fire', 'air', 'water'],
                  'type': 'unique',
                  'description': '对目标地的每个入侵者各造成 1 伤害。',
                  'threshold': {},
                  'spirit': 'lightning'},
 'boon_of_vigor': {'name': '活力恩泽',
                   'name_en': 'Boon of Vigor',
                   'cost': 0,
                   'speed': 'fast',
                   'range': None,
                   'target': 'spirit',
                   'target_filter': {},
                   'sacred_site': False,
                   'elements': ['sun', 'water', 'plant'],
                   'type': 'unique',
                   'description': '对自己：获得 1 能量；对其他精灵：其本轮每张已打出牌提供 1 能量。',
                   'threshold': {},
                   'spirit': 'river'},
 'rivers_bounty': {'name': '河流馈赠',
                   'name_en': "River's Bounty",
                   'cost': 0,
                   'speed': 'slow',
                   'range': 0,
                   'target': 'land',
                   'target_filter': {},
                   'sacred_site': False,
                   'elements': ['sun', 'water', 'animal'],
                   'type': 'unique',
                   'description': '聚集至多 2 达汉。随后若至少有 2 达汉，增加 1 达汉并获得 1 能量。',
                   'threshold': {},
                   'spirit': 'river'},
 'wash_away': {'name': '冲刷而去',
               'name_en': 'Wash Away',
               'cost': 1,
               'speed': 'slow',
               'range': 1,
               'target': 'land',
               'target_filter': {},
               'sacred_site': False,
               'elements': ['water', 'earth'],
               'type': 'unique',
               'description': '推离合计至多 3 个探索者或村镇。',
               'threshold': {},
               'spirit': 'river'},
 'flash_floods': {'name': '骤发洪流',
                  'name_en': 'Flash Floods',
                  'cost': 2,
                  'speed': 'fast',
                  'range': 1,
                  'target': 'land',
                  'target_filter': {},
                  'sacred_site': False,
                  'elements': ['sun', 'water'],
                  'type': 'unique',
                  'description': '造成 1 伤害；沿海土地再加 1 伤害。',
                  'threshold': {},
                  'spirit': 'river'},
 'natures_resilience': {'name': '自然韧性',
                        'name_en': "Nature's Resilience",
                        'cost': 1,
                        'speed': 'fast',
                        'range': 1,
                        'target': 'land',
                        'target_filter': {},
                        'sacred_site': True,
                        'elements': ['earth', 'plant', 'animal'],
                        'type': 'minor',
                        'description': '提供 6 防御；达到 2 水门槛时，可改为移除 1 荒芜。',
                        'threshold': {'water': 2}},
 'call_to_tend': {'name': '照料召唤',
                  'name_en': 'Call to Tend',
                  'cost': 1,
                  'speed': 'slow',
                  'range': 1,
                  'target': 'land',
                  'target_filter': {'dahan': True},
                  'sacred_site': False,
                  'elements': ['water', 'plant', 'animal'],
                  'type': 'minor',
                  'description': '二选一：移除 1 荒芜；或推离至多 3 达汉。',
                  'threshold': {}},
 'drift_down_into_slumber': {'name': '安然入眠',
                             'name_en': 'Drift Down into Slumber',
                             'cost': 0,
                             'speed': 'fast',
                             'range': 2,
                             'target': 'land',
                             'target_filter': {},
                             'sacred_site': False,
                             'elements': ['air', 'earth', 'plant'],
                             'type': 'minor',
                             'description': '提供 1 防御；丛林或沙地改为 4 防御。',
                             'threshold': {}},
 'drought': {'name': '旱灾',
             'name_en': 'Drought',
             'cost': 1,
             'speed': 'slow',
             'range': 1,
             'target': 'land',
             'target_filter': {},
             'sacred_site': False,
             'elements': ['sun', 'fire', 'earth'],
             'type': 'minor',
             'description': '摧毁 3 村镇，再对每个村镇和城市各造成 1 伤害，增加 1 荒芜；达到 3 日门槛后再摧毁 1 城市。',
             'threshold': {'sun': 3}},
 'elemental_boon': {'name': '元素恩泽',
                    'name_en': 'Elemental Boon',
                    'cost': 1,
                    'speed': 'fast',
                    'range': None,
                    'target': 'spirit',
                    'target_filter': {},
                    'sacred_site': False,
                    'elements': [],
                    'type': 'minor',
                    'description': '目标获得自选的 3 种不同元素；若目标为其他精灵，你也获得相同元素。',
                    'threshold': {}},
 'enticing_splendor': {'name': '诱人异彩',
                       'name_en': 'Enticing Splendor',
                       'cost': 0,
                       'speed': 'fast',
                       'range': 0,
                       'target': 'land',
                       'target_filter': {'no_blight': True},
                       'sacred_site': False,
                       'elements': ['sun', 'air', 'plant'],
                       'type': 'minor',
                       'description': '二选一：聚集 1 探索者或村镇；或聚集至多 2 达汉。',
                       'threshold': {}},
 'gift_of_constancy': {'name': '恒常赐福',
                       'name_en': 'Gift of Constancy',
                       'cost': 0,
                       'speed': 'fast',
                       'range': None,
                       'target': 'spirit',
                       'target_filter': {},
                       'sacred_site': False,
                       'elements': ['sun', 'earth'],
                       'type': 'minor',
                       'description': '目标获得 2 能量，回合结束可收回 1 张本轮使用的牌；若目标是其他精灵，你也可这样收回 1 张。',
                       'threshold': {}},
 'gift_of_living_energy': {'name': '生命能量',
                           'name_en': 'Gift of Living Energy',
                           'cost': 0,
                           'speed': 'fast',
                           'range': None,
                           'target': 'spirit',
                           'target_filter': {},
                           'sacred_site': False,
                           'elements': ['sun', 'fire', 'plant'],
                           'type': 'minor',
                           'description': '目标获得 1 能量；你至少有 2 圣地时再加 1；目标为其他精灵时再加 1。',
                           'threshold': {}},
 'gift_of_power': {'name': '力量赐福',
                   'name_en': 'Gift of Power',
                   'cost': 0,
                   'speed': 'slow',
                   'range': None,
                   'target': 'spirit',
                   'target_filter': {},
                   'sacred_site': False,
                   'elements': ['moon', 'water', 'earth', 'plant'],
                   'type': 'minor',
                   'description': '目标学习 1 张小力量。',
                   'threshold': {}},
 'gnawing_rootbiters': {'name': '啃根兽群',
                        'name_en': 'Gnawing Rootbiters',
                        'cost': 0,
                        'speed': 'slow',
                        'range': 1,
                        'target': 'land',
                        'target_filter': {},
                        'sacred_site': False,
                        'elements': ['earth', 'animal'],
                        'type': 'minor',
                        'description': '推离至多 2 村镇。',
                        'threshold': {}},
 'lure_of_the_unknown': {'name': '未知诱惑',
                         'name_en': 'Lure of the Unknown',
                         'cost': 0,
                         'speed': 'fast',
                         'range': 2,
                         'target': 'land',
                         'target_filter': {'no_invaders': True},
                         'sacred_site': False,
                         'elements': ['moon', 'fire', 'air', 'plant'],
                         'type': 'minor',
                         'description': '聚集 1 探索者或村镇。',
                         'threshold': {}},
 'quicken_the_earths_struggles': {'name': '大地挣扎',
                                  'name_en': "Quicken the Earth's Struggles",
                                  'cost': 1,
                                  'speed': 'fast',
                                  'range': 0,
                                  'target': 'land',
                                  'target_filter': {},
                                  'sacred_site': True,
                                  'elements': ['moon', 'fire', 'earth', 'animal'],
                                  'type': 'minor',
                                  'description': '二选一：每个村镇和城市各受 1 伤害；或提供 10 防御。',
                                  'threshold': {}},
 'rain_of_blood': {'name': '血雨',
                   'name_en': 'Rain of Blood',
                   'cost': 0,
                   'speed': 'slow',
                   'range': 1,
                   'target': 'land',
                   'target_filter': {'invaders': True},
                   'sacred_site': True,
                   'elements': ['air', 'water', 'animal'],
                   'type': 'minor',
                   'description': '产生 2 恐惧；村镇与城市合计至少 2 个时，再产生 1 恐惧。',
                   'threshold': {}},
 'reaching_grasp': {'name': '延伸之握',
                    'name_en': 'Reaching Grasp',
                    'cost': 0,
                    'speed': 'fast',
                    'range': None,
                    'target': 'spirit',
                    'target_filter': {},
                    'sacred_site': False,
                    'elements': ['sun', 'air', 'water'],
                    'type': 'minor',
                    'description': '目标本轮所有力量的距离增加 2。',
                    'threshold': {}},
 'sap_the_strength_of_multitudes': {'name': '削弱群敌',
                                    'name_en': 'Sap the Strength of Multitudes',
                                    'cost': 0,
                                    'speed': 'fast',
                                    'range': 0,
                                    'target': 'land',
                                    'target_filter': {},
                                    'sacred_site': False,
                                    'elements': ['water', 'animal'],
                                    'type': 'minor',
                                    'description': '提供 5 防御；达到 1 风门槛时，本力量距离从 0 提升至 1。',
                                    'threshold': {'air': 1}},
 'steam_vents': {'name': '蒸汽喷口',
                 'name_en': 'Steam Vents',
                 'cost': 1,
                 'speed': 'fast',
                 'range': 0,
                 'target': 'land',
                 'target_filter': {},
                 'sacred_site': False,
                 'elements': ['fire', 'air', 'water', 'earth'],
                 'type': 'minor',
                 'description': '摧毁 1 探索者；达到 3 土门槛可改为摧毁 1 村镇。',
                 'threshold': {'earth': 3}},
 'veil_the_nights_hunt': {'name': '夜猎帷幕',
                          'name_en': "Veil the Night's Hunt",
                          'cost': 1,
                          'speed': 'fast',
                          'range': 2,
                          'target': 'land',
                          'target_filter': {'dahan': True},
                          'sacred_site': False,
                          'elements': ['moon', 'air', 'animal'],
                          'type': 'minor',
                          'description': '二选一：每个达汉选择不同入侵者，对每个被选者造成 1 伤害；或推离至多 3 达汉。',
                          'threshold': {}},
 'blazing_renewal': {'name': '烈焰新生',
                     'name_en': 'Blazing Renewal',
                     'cost': 5,
                     'speed': 'fast',
                     'range': None,
                     'target': 'spirit',
                     'target_filter': {},
                     'sacred_site': False,
                     'elements': ['fire', 'earth', 'plant'],
                     'type': 'major',
                     'description': '目标把 2 枚被摧毁的存在放回你距离 2 内的同一土地（不足则尽量）。成功放回后，对当地每个村镇和城市各造成 2 伤害；门槛再造成 4 伤害。',
                     'threshold': {'fire': 3, 'earth': 3, 'plant': 2}},
 'cleansing_floods': {'name': '净化洪流',
                      'name_en': 'Cleansing Floods',
                      'cost': 5,
                      'speed': 'slow',
                      'range': 1,
                      'target': 'land',
                      'target_filter': {},
                      'sacred_site': False,
                      'elements': ['sun', 'water'],
                      'type': 'major',
                      'description': '造成 4 伤害并移除 1 荒芜；达到 4 水门槛再造成 10 伤害。',
                      'threshold': {'water': 4},
                      'source_terrain': 'wetland'},
 'dissolve_the_bonds_of_kinship': {'name': '瓦解族群纽带',
                                   'name_en': 'Dissolve the Bonds of Kinship',
                                   'cost': 4,
                                   'speed': 'slow',
                                   'range': 1,
                                   'target': 'land',
                                   'target_filter': {},
                                   'sacred_site': False,
                                   'elements': ['fire', 'water', 'animal'],
                                   'type': 'major',
                                   'description': '将 1 城市变为 2 探索者、1 村镇变为 1 探索者、1 达汉变为 1 '
                                                  '探索者；推离全部探索者，尽可能分散至不同邻地。门槛使推离前探索者与建筑互相造成伤害。',
                                   'threshold': {'fire': 2, 'water': 2, 'animal': 3}},
 'entwined_power': {'name': '交织力量',
                    'name_en': 'Entwined Power',
                    'cost': 2,
                    'speed': 'fast',
                    'range': None,
                    'target': 'other_spirit',
                    'target_filter': {},
                    'sacred_site': False,
                    'elements': ['moon', 'water', 'plant'],
                    'type': 'major',
                    'description': '本轮双方可借用对方存在确定力量目标。目标学习力量，你取得其未选的一张。门槛使双方各获 3 能量，并可互赠手牌。',
                    'threshold': {'water': 2, 'plant': 4}},
 'indomitable_claim': {'name': '不屈宣告',
                       'name_en': 'Indomitable Claim',
                       'cost': 4,
                       'speed': 'fast',
                       'range': 1,
                       'target': 'land',
                       'target_filter': {},
                       'sacred_site': False,
                       'elements': ['sun', 'earth'],
                       'type': 'major',
                       'description': '从轨道放置 1 存在，提供 20 防御；门槛跳过当地全部入侵者行动，若有入侵者还产生 3 恐惧。',
                       'threshold': {'sun': 2, 'earth': 3}},
 'infinite_vitality': {'name': '无尽生机',
                       'name_en': 'Infinite Vitality',
                       'cost': 3,
                       'speed': 'fast',
                       'range': 1,
                       'target': 'land',
                       'target_filter': {},
                       'sacred_site': True,
                       'elements': ['earth', 'plant', 'animal'],
                       'type': 'major',
                       'description': '本轮当地达汉生命值增加 4，并阻止添加荒芜；达到 4 土门槛还使达汉不受伤害与摧毁，并从本地或邻地移除 1 荒芜。',
                       'threshold': {'earth': 4}},
 'mists_of_oblivion': {'name': '遗忘迷雾',
                       'name_en': 'Mists of Oblivion',
                       'cost': 4,
                       'speed': 'slow',
                       'range': 3,
                       'target': 'land',
                       'target_filter': {},
                       'sacred_site': False,
                       'elements': ['moon', 'air', 'water'],
                       'type': 'major',
                       'description': '每个入侵者各受 1 伤害；此力量每摧毁 1 建筑额外产生 1 恐惧，上限 4。门槛额外造成 3 伤害。',
                       'threshold': {'moon': 2, 'air': 3, 'water': 2}},
 'paralyzing_fright': {'name': '惊惧麻痹',
                       'name_en': 'Paralyzing Fright',
                       'cost': 4,
                       'speed': 'fast',
                       'range': 1,
                       'target': 'land',
                       'target_filter': {},
                       'sacred_site': True,
                       'elements': ['air', 'earth'],
                       'type': 'major',
                       'description': '产生 4 恐惧，跳过当地所有入侵者行动；门槛再产生 4 恐惧。',
                       'threshold': {'air': 2, 'earth': 3}},
 'talons_of_lightning': {'name': '闪电利爪',
                         'name_en': 'Talons of Lightning',
                         'cost': 6,
                         'speed': 'fast',
                         'range': 1,
                         'target': 'land',
                         'target_filter': {'terrain': ['mountain', 'wetland']},
                         'sacred_site': False,
                         'elements': ['fire', 'air'],
                         'type': 'major',
                         'description': '产生 3 恐惧、造成 5 伤害；门槛将距离提升至 3，并在每个邻地摧毁 1 村镇。',
                         'threshold': {'fire': 3, 'air': 3}},
 'the_land_thrashes_in_furious_pain': {'name': '大地痛苦翻腾',
                                       'name_en': 'The Land Thrashes in Furious Pain',
                                       'cost': 4,
                                       'speed': 'slow',
                                       'range': 2,
                                       'target': 'land',
                                       'target_filter': {'blight': True},
                                       'sacred_site': False,
                                       'elements': ['moon', 'fire', 'earth'],
                                       'type': 'major',
                                       'description': '按本地每个荒芜造成 2 伤害，加上邻地每个荒芜造成 1 '
                                                      '伤害；门槛在一块邻地重复本力量，忽略距离及目标限制。',
                                       'threshold': {'moon': 3, 'earth': 3}},
 'the_trees_and_stones_speak_of_war': {'name': '树石言战',
                                       'name_en': 'The Trees and Stones Speak of War',
                                       'cost': 2,
                                       'speed': 'fast',
                                       'range': 1,
                                       'target': 'land',
                                       'target_filter': {'dahan': True},
                                       'sacred_site': False,
                                       'elements': ['sun', 'earth', 'plant'],
                                       'type': 'major',
                                       'description': '每个达汉造成 1 伤害并提供 2 防御；门槛可推离至多 2 达汉，每个随行转移 2 防御。',
                                       'threshold': {'sun': 2, 'earth': 2, 'plant': 2}},
 'vengeance_of_the_dead': {'name': '亡者复仇',
                           'name_en': 'Vengeance of the Dead',
                           'cost': 3,
                           'speed': 'fast',
                           'range': 3,
                           'target': 'land',
                           'target_filter': {},
                           'sacred_site': False,
                           'elements': ['moon', 'fire', 'animal'],
                           'type': 'major',
                           'description': '产生 3 恐惧。本轮该地村镇、城市或达汉被摧毁后，每个触发 1 伤害（不能自我触发）；门槛允许将伤害分配到邻地。',
                           'threshold': {'animal': 3}},
 'winds_of_rust_and_atrophy': {'name': '锈蚀衰朽之风',
                               'name_en': 'Winds of Rust and Atrophy',
                               'cost': 3,
                               'speed': 'fast',
                               'range': 3,
                               'target': 'land',
                               'target_filter': {},
                               'sacred_site': True,
                               'elements': ['air', 'water', 'animal'],
                               'type': 'major',
                               'description': '产生 1 恐惧，提供 6 防御，并把 1 村镇或城市降低一级；门槛再重复本力量一次。',
                               'threshold': {'air': 3, 'water': 3, 'animal': 2}},
 'wrap_in_wings_of_sunlight': {'name': '日光羽翼',
                               'name_en': 'Wrap in Wings of Sunlight',
                               'cost': 3,
                               'speed': 'fast',
                               'range': 0,
                               'target': 'land',
                               'target_filter': {},
                               'sacred_site': False,
                               'elements': ['sun', 'air', 'animal'],
                               'type': 'major',
                               'description': '把至多 5 达汉移动到任意同一土地（可回原地）；移动至少 1 个时，该地获得 5 防御。门槛可在移动前聚集至多 3 达汉。',
                               'threshold': {'sun': 2, 'air': 2, 'animal': 2}}}

FEAR_CARDS: Dict = {'avoid_the_dahan': {'name': '避开达汉',
                     'name_en': 'Avoid the Dahan',
                     'level1': '至少 2 达汉的土地跳过探索。',
                     'level2': '达汉数多于村镇与城市总数的土地跳过建造（包括没有建筑的土地）。',
                     'level3': '有达汉的土地跳过建造。'},
 'belief_takes_root': {'name': '信念生根',
                       'name_en': 'Belief Takes Root',
                       'level1': '所有含存在的土地获得 2 防御。',
                       'level2': '所有含存在的土地获得 2 防御；各精灵按自己有入侵者的圣地数量获得能量。',
                       'level3': '各玩家选择不同土地，每枚存在可移除总生命值 2 的入侵者。'},
 'dahan_enheartened': {'name': '达汉振奋',
                       'name_en': 'Dahan Enheartened',
                       'level1': '各玩家可从含入侵者的土地推离 1 达汉，或向含入侵者的土地聚集 1 达汉。',
                       'level2': '各玩家选择不同土地，聚集至多 2 达汉；随后若有达汉，造成 1 伤害。',
                       'level3': '各玩家选择不同土地，聚集至多 2 达汉；随后每个达汉造成 1 伤害。'},
 'dahan_on_their_guard': {'name': '达汉戒备',
                          'name_en': 'Dahan on their Guard',
                          'level1': '每个达汉在当地提供 1 防御。',
                          'level2': '有达汉的土地获得 1 防御，再按每个达汉增加 1 防御。',
                          'level3': '每个达汉在当地提供 2 防御。'},
 'dahan_raid': {'name': '达汉突袭',
                'name_en': 'Dahan Raid',
                'level1': '各玩家选择不同的有达汉土地，造成 1 伤害。',
                'level2': '各玩家选择不同的有达汉土地，每个达汉造成 1 伤害。',
                'level3': '各玩家选择不同的有达汉土地，每个达汉造成 2 伤害。'},
 'emigration_accelerates': {'name': '加速离岛',
                            'name_en': 'Emigration Accelerates',
                            'level1': '各玩家从沿海地移除 1 探索者。',
                            'level2': '各玩家从沿海地移除 1 探索者或村镇。',
                            'level3': '各玩家从任意土地移除 1 探索者或村镇。'},
 'fear_of_the_unseen': {'name': '畏惧未知',
                        'name_en': 'Fear of the Unseen',
                        'level1': '各玩家从含圣地的土地移除 1 探索者或村镇。',
                        'level2': '各玩家从含存在的土地移除 1 探索者或村镇。',
                        'level3': '各玩家移除含存在土地的 1 探索者或村镇，或含圣地土地的 1 城市。'},
 'isolation': {'name': '孤立无援',
               'name_en': 'Isolation',
               'level1': '各玩家从只有 1 入侵者的土地移除 1 探索者或村镇。',
               'level2': '各玩家从至多 2 入侵者的土地移除 1 探索者或村镇。',
               'level3': '各玩家从至多 2 入侵者的土地移除 1 入侵者。'},
 'overseas_trade_seems_safer': {'name': '转向海外贸易',
                                'name_en': 'Overseas Trade Seems Safer',
                                'level1': '所有沿海地获得 3 防御。',
                                'level2': '所有沿海地获得 6 防御，并跳过会建造城市的建造行动。',
                                'level3': '所有沿海地获得 9 防御，并跳过建造。'},
 'retreat': {'name': '撤退',
             'name_en': 'Retreat!',
             'level1': '各玩家可从一块内陆地推离至多 2 探索者。',
             'level2': '各玩家可从一块内陆地推离合计至多 3 探索者或村镇。',
             'level3': '各玩家可从一块土地推离任意数量探索者或村镇。'},
 'scapegoats': {'name': '寻找替罪羊',
                'name_en': 'Scapegoats',
                'level1': '每块有村镇的土地，按每个村镇摧毁 1 探索者。',
                'level2': '每块有建筑的土地，每个村镇摧毁 1 探索者、每个城市摧毁 2 探索者。',
                'level3': '每块有建筑的土地摧毁全部探索者；每个城市再摧毁 1 村镇。'},
 'seek_safety': {'name': '寻求庇护',
                 'name_en': 'Seek Safety',
                 'level1': '各玩家可推离 1 探索者，其目的地建筑数必须多于起点。',
                 'level2': '各玩家可向有建筑的土地聚集 1 探索者，或向有城市的土地聚集 1 村镇。',
                 'level3': '各玩家可从没有城市的土地移除总生命值至多 3 的入侵者。'},
 'tall_tales_of_savagery': {'name': '骇人的传闻',
                            'name_en': 'Tall Tales of Savagery',
                            'level1': '各玩家从有达汉的土地移除 1 探索者。',
                            'level2': '各玩家从有达汉的土地移除 2 探索者或 1 村镇。',
                            'level3': '每块有达汉的土地移除 2 探索者或 1 村镇；至少 2 达汉时再移除 1 城市。'},
 'trade_suffers': {'name': '贸易受阻',
                   'name_en': 'Trade Suffers',
                   'level1': '有城市的土地跳过建造。',
                   'level2': '各玩家可将沿海地的 1 村镇降为探索者。',
                   'level3': '各玩家可将沿海地的 1 村镇或城市降低一级。'},
 'wary_of_the_interior': {'name': '畏惧内陆',
                          'name_en': 'Wary of the Interior',
                          'level1': '各玩家从内陆地移除 1 探索者。',
                          'level2': '各玩家从内陆地移除 1 探索者或村镇。',
                          'level3': '各玩家从任意土地移除 1 探索者或村镇。'}}
