# Auto-generated from TheGoldenChicken/splendor cards.json
# Contains Splendor classic card/noble data.

COLORS = ['white', 'blue', 'green', 'red', 'black']
TOKEN_COLORS = ['white', 'blue', 'green', 'red', 'black', 'gold']

TIER_DECKS = {
    'tier1': [
        {'id': 'L1-01', 'tier': 1, 'points': 1, 'bonus': 'white', 'cost': {'green': 4}},
        {'id': 'L1-02', 'tier': 1, 'points': 0, 'bonus': 'white', 'cost': {'blue': 3}},
        {'id': 'L1-03', 'tier': 1, 'points': 0, 'bonus': 'white', 'cost': {'red': 2, 'black': 1}},
        {'id': 'L1-04', 'tier': 1, 'points': 0, 'bonus': 'white', 'cost': {'blue': 2, 'black': 2}},
        {'id': 'L1-05', 'tier': 1, 'points': 0, 'bonus': 'white', 'cost': {'blue': 1, 'green': 1, 'red': 1, 'black': 1}},
        {'id': 'L1-06', 'tier': 1, 'points': 0, 'bonus': 'white', 'cost': {'blue': 1, 'green': 2, 'red': 1, 'black': 1}},
        {'id': 'L1-07', 'tier': 1, 'points': 0, 'bonus': 'white', 'cost': {'blue': 2, 'green': 2, 'black': 1}},
        {'id': 'L1-08', 'tier': 1, 'points': 0, 'bonus': 'white', 'cost': {'white': 3, 'blue': 1, 'black': 1}},
        {'id': 'L1-09', 'tier': 1, 'points': 1, 'bonus': 'blue', 'cost': {'red': 4}},
        {'id': 'L1-10', 'tier': 1, 'points': 0, 'bonus': 'blue', 'cost': {'black': 3}},
        {'id': 'L1-11', 'tier': 1, 'points': 0, 'bonus': 'blue', 'cost': {'white': 1, 'black': 2}},
        {'id': 'L1-12', 'tier': 1, 'points': 0, 'bonus': 'blue', 'cost': {'green': 2, 'black': 2}},
        {'id': 'L1-13', 'tier': 1, 'points': 0, 'bonus': 'blue', 'cost': {'white': 1, 'green': 1, 'red': 1, 'black': 1}},
        {'id': 'L1-14', 'tier': 1, 'points': 0, 'bonus': 'blue', 'cost': {'white': 1, 'green': 1, 'red': 2, 'black': 1}},
        {'id': 'L1-15', 'tier': 1, 'points': 0, 'bonus': 'blue', 'cost': {'white': 1, 'green': 2, 'red': 2}},
        {'id': 'L1-16', 'tier': 1, 'points': 0, 'bonus': 'blue', 'cost': {'blue': 1, 'green': 3, 'red': 1}},
        {'id': 'L1-17', 'tier': 1, 'points': 1, 'bonus': 'green', 'cost': {'black': 4}},
        {'id': 'L1-18', 'tier': 1, 'points': 0, 'bonus': 'green', 'cost': {'red': 3}},
        {'id': 'L1-19', 'tier': 1, 'points': 0, 'bonus': 'green', 'cost': {'white': 2, 'blue': 1}},
        {'id': 'L1-20', 'tier': 1, 'points': 0, 'bonus': 'green', 'cost': {'blue': 2, 'red': 2}},
        {'id': 'L1-21', 'tier': 1, 'points': 0, 'bonus': 'green', 'cost': {'white': 1, 'blue': 1, 'red': 1, 'black': 1}},
        {'id': 'L1-22', 'tier': 1, 'points': 0, 'bonus': 'green', 'cost': {'white': 1, 'blue': 1, 'red': 1, 'black': 2}},
        {'id': 'L1-23', 'tier': 1, 'points': 0, 'bonus': 'green', 'cost': {'blue': 1, 'red': 2, 'black': 2}},
        {'id': 'L1-24', 'tier': 1, 'points': 0, 'bonus': 'green', 'cost': {'white': 1, 'blue': 3, 'green': 1}},
        {'id': 'L1-25', 'tier': 1, 'points': 1, 'bonus': 'red', 'cost': {'white': 4}},
        {'id': 'L1-26', 'tier': 1, 'points': 0, 'bonus': 'red', 'cost': {'white': 3}},
        {'id': 'L1-27', 'tier': 1, 'points': 0, 'bonus': 'red', 'cost': {'blue': 2, 'green': 1}},
        {'id': 'L1-28', 'tier': 1, 'points': 0, 'bonus': 'red', 'cost': {'white': 2, 'red': 2}},
        {'id': 'L1-29', 'tier': 1, 'points': 0, 'bonus': 'red', 'cost': {'white': 1, 'blue': 1, 'green': 1, 'black': 1}},
        {'id': 'L1-30', 'tier': 1, 'points': 0, 'bonus': 'red', 'cost': {'white': 2, 'blue': 1, 'green': 1, 'black': 1}},
        {'id': 'L1-31', 'tier': 1, 'points': 0, 'bonus': 'red', 'cost': {'white': 2, 'green': 1, 'black': 2}},
        {'id': 'L1-32', 'tier': 1, 'points': 0, 'bonus': 'red', 'cost': {'white': 1, 'red': 1, 'black': 3}},
        {'id': 'L1-33', 'tier': 1, 'points': 1, 'bonus': 'black', 'cost': {'blue': 4}},
        {'id': 'L1-34', 'tier': 1, 'points': 0, 'bonus': 'black', 'cost': {'green': 3}},
        {'id': 'L1-35', 'tier': 1, 'points': 0, 'bonus': 'black', 'cost': {'green': 2, 'red': 1}},
        {'id': 'L1-36', 'tier': 1, 'points': 0, 'bonus': 'black', 'cost': {'white': 2, 'green': 2}},
        {'id': 'L1-37', 'tier': 1, 'points': 0, 'bonus': 'black', 'cost': {'white': 1, 'blue': 1, 'green': 1, 'red': 1}},
        {'id': 'L1-38', 'tier': 1, 'points': 0, 'bonus': 'black', 'cost': {'white': 1, 'blue': 2, 'green': 1, 'red': 1}},
        {'id': 'L1-39', 'tier': 1, 'points': 0, 'bonus': 'black', 'cost': {'white': 2, 'blue': 2, 'red': 1}},
        {'id': 'L1-40', 'tier': 1, 'points': 0, 'bonus': 'black', 'cost': {'green': 1, 'red': 3, 'black': 1}},
    ],
    'tier2': [
        {'id': 'L2-01', 'tier': 2, 'points': 3, 'bonus': 'white', 'cost': {'white': 6}},
        {'id': 'L2-02', 'tier': 2, 'points': 2, 'bonus': 'white', 'cost': {'red': 5}},
        {'id': 'L2-03', 'tier': 2, 'points': 2, 'bonus': 'white', 'cost': {'red': 5, 'black': 3}},
        {'id': 'L2-04', 'tier': 2, 'points': 2, 'bonus': 'white', 'cost': {'green': 1, 'red': 4, 'black': 2}},
        {'id': 'L2-05', 'tier': 2, 'points': 1, 'bonus': 'white', 'cost': {'green': 3, 'red': 2, 'black': 2}},
        {'id': 'L2-06', 'tier': 2, 'points': 1, 'bonus': 'white', 'cost': {'white': 2, 'blue': 3, 'red': 3}},
        {'id': 'L2-07', 'tier': 2, 'points': 3, 'bonus': 'blue', 'cost': {'blue': 6}},
        {'id': 'L2-08', 'tier': 2, 'points': 2, 'bonus': 'blue', 'cost': {'blue': 5}},
        {'id': 'L2-09', 'tier': 2, 'points': 2, 'bonus': 'blue', 'cost': {'white': 5, 'blue': 3}},
        {'id': 'L2-10', 'tier': 2, 'points': 2, 'bonus': 'blue', 'cost': {'white': 2, 'red': 1, 'black': 4}},
        {'id': 'L2-11', 'tier': 2, 'points': 1, 'bonus': 'blue', 'cost': {'blue': 2, 'green': 2, 'red': 3}},
        {'id': 'L2-12', 'tier': 2, 'points': 1, 'bonus': 'blue', 'cost': {'blue': 2, 'green': 3, 'black': 3}},
        {'id': 'L2-13', 'tier': 2, 'points': 3, 'bonus': 'green', 'cost': {'green': 6}},
        {'id': 'L2-14', 'tier': 2, 'points': 2, 'bonus': 'green', 'cost': {'green': 5}},
        {'id': 'L2-15', 'tier': 2, 'points': 2, 'bonus': 'green', 'cost': {'blue': 5, 'green': 3}},
        {'id': 'L2-16', 'tier': 2, 'points': 2, 'bonus': 'green', 'cost': {'white': 4, 'blue': 2, 'black': 1}},
        {'id': 'L2-17', 'tier': 2, 'points': 1, 'bonus': 'green', 'cost': {'white': 2, 'blue': 3, 'black': 2}},
        {'id': 'L2-18', 'tier': 2, 'points': 1, 'bonus': 'green', 'cost': {'white': 3, 'green': 2, 'red': 3}},
        {'id': 'L2-19', 'tier': 2, 'points': 3, 'bonus': 'red', 'cost': {'red': 6}},
        {'id': 'L2-20', 'tier': 2, 'points': 2, 'bonus': 'red', 'cost': {'black': 5}},
        {'id': 'L2-21', 'tier': 2, 'points': 2, 'bonus': 'red', 'cost': {'white': 3, 'black': 5}},
        {'id': 'L2-22', 'tier': 2, 'points': 2, 'bonus': 'red', 'cost': {'white': 1, 'blue': 4, 'green': 2}},
        {'id': 'L2-23', 'tier': 2, 'points': 1, 'bonus': 'red', 'cost': {'white': 2, 'red': 2, 'black': 3}},
        {'id': 'L2-24', 'tier': 2, 'points': 1, 'bonus': 'red', 'cost': {'blue': 3, 'red': 2, 'black': 3}},
        {'id': 'L2-25', 'tier': 2, 'points': 3, 'bonus': 'black', 'cost': {'black': 6}},
        {'id': 'L2-26', 'tier': 2, 'points': 2, 'bonus': 'black', 'cost': {'white': 5}},
        {'id': 'L2-27', 'tier': 2, 'points': 2, 'bonus': 'black', 'cost': {'green': 5, 'red': 3}},
        {'id': 'L2-28', 'tier': 2, 'points': 2, 'bonus': 'black', 'cost': {'blue': 1, 'green': 4, 'red': 2}},
        {'id': 'L2-29', 'tier': 2, 'points': 1, 'bonus': 'black', 'cost': {'white': 3, 'blue': 2, 'green': 2}},
        {'id': 'L2-30', 'tier': 2, 'points': 1, 'bonus': 'black', 'cost': {'white': 3, 'green': 3, 'black': 2}},
    ],
    'tier3': [
        {'id': 'L3-01', 'tier': 3, 'points': 5, 'bonus': 'white', 'cost': {'white': 3, 'black': 7}},
        {'id': 'L3-02', 'tier': 3, 'points': 4, 'bonus': 'white', 'cost': {'black': 7}},
        {'id': 'L3-03', 'tier': 3, 'points': 4, 'bonus': 'white', 'cost': {'white': 3, 'red': 3, 'black': 6}},
        {'id': 'L3-04', 'tier': 3, 'points': 3, 'bonus': 'white', 'cost': {'blue': 3, 'green': 3, 'red': 5, 'black': 3}},
        {'id': 'L3-05', 'tier': 3, 'points': 5, 'bonus': 'blue', 'cost': {'white': 7, 'blue': 3}},
        {'id': 'L3-06', 'tier': 3, 'points': 4, 'bonus': 'blue', 'cost': {'white': 7}},
        {'id': 'L3-07', 'tier': 3, 'points': 4, 'bonus': 'blue', 'cost': {'white': 6, 'blue': 3, 'black': 3}},
        {'id': 'L3-08', 'tier': 3, 'points': 3, 'bonus': 'blue', 'cost': {'white': 3, 'green': 3, 'red': 3, 'black': 5}},
        {'id': 'L3-09', 'tier': 3, 'points': 5, 'bonus': 'green', 'cost': {'blue': 7, 'green': 3}},
        {'id': 'L3-10', 'tier': 3, 'points': 4, 'bonus': 'green', 'cost': {'blue': 7}},
        {'id': 'L3-11', 'tier': 3, 'points': 4, 'bonus': 'green', 'cost': {'white': 3, 'blue': 6, 'green': 3}},
        {'id': 'L3-12', 'tier': 3, 'points': 3, 'bonus': 'green', 'cost': {'white': 5, 'blue': 3, 'red': 3, 'black': 3}},
        {'id': 'L3-13', 'tier': 3, 'points': 5, 'bonus': 'red', 'cost': {'green': 7, 'red': 3}},
        {'id': 'L3-14', 'tier': 3, 'points': 4, 'bonus': 'red', 'cost': {'green': 7}},
        {'id': 'L3-15', 'tier': 3, 'points': 4, 'bonus': 'red', 'cost': {'blue': 3, 'green': 6, 'red': 3}},
        {'id': 'L3-16', 'tier': 3, 'points': 3, 'bonus': 'red', 'cost': {'white': 3, 'blue': 5, 'green': 3, 'black': 3}},
        {'id': 'L3-17', 'tier': 3, 'points': 5, 'bonus': 'black', 'cost': {'red': 7, 'black': 3}},
        {'id': 'L3-18', 'tier': 3, 'points': 4, 'bonus': 'black', 'cost': {'red': 7}},
        {'id': 'L3-19', 'tier': 3, 'points': 4, 'bonus': 'black', 'cost': {'green': 3, 'red': 6, 'black': 3}},
        {'id': 'L3-20', 'tier': 3, 'points': 3, 'bonus': 'black', 'cost': {'white': 3, 'blue': 3, 'green': 5, 'red': 3}},
    ],
}

NOBLES = [
    {'id': 'N-01', 'points': 3, 'requirement': {'white': 3, 'blue': 3, 'green': 3}},
    {'id': 'N-02', 'points': 3, 'requirement': {'white': 3, 'red': 3, 'black': 3}},
    {'id': 'N-03', 'points': 3, 'requirement': {'white': 3, 'blue': 3, 'black': 3}},
    {'id': 'N-04', 'points': 3, 'requirement': {'green': 3, 'red': 3, 'black': 3}},
    {'id': 'N-05', 'points': 3, 'requirement': {'blue': 3, 'green': 3, 'red': 3}},
    {'id': 'N-06', 'points': 3, 'requirement': {'blue': 4, 'green': 4}},
    {'id': 'N-07', 'points': 3, 'requirement': {'white': 4, 'black': 4}},
    {'id': 'N-08', 'points': 3, 'requirement': {'red': 4, 'black': 4}},
    {'id': 'N-09', 'points': 3, 'requirement': {'white': 4, 'blue': 4}},
    {'id': 'N-10', 'points': 3, 'requirement': {'green': 4, 'red': 4}},
]
