# Auto-generated from designs/8.1.cards.md

DAY_DECKS = {
    1: [
        {
            'id': 1,
            'day': 1,
            'year': -37000,
            'year_label': "37,000 BCE",
            'title': "Leave your handprint in the Maros-Pangkep caves",
            'cost': 3,
            'reward_raw': "\u8fdb\u6b65",
            'tokens': ["progress"],
        },
        {
            'id': 2,
            'day': 1,
            'year': -12000,
            'year_label': "12,000 BCE",
            'title': "Hunt bison with an atlatl",
            'cost': 2,
            'reward_raw': "\u521b\u65b0",
            'tokens': ["innovation"],
        },
        {
            'id': 3,
            'day': 1,
            'year': -2000,
            'year_label': "2000 BCE",
            'title': "Take a dip in The Great Bath",
            'cost': 2,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 4,
            'day': 1,
            'year': -1772,
            'year_label': "1772 BCE",
            'title': "Discuss the code of law with Hammurabi",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u8fdb\u6b65",
            'tokens': ["person", "progress"],
        },
        {
            'id': 5,
            'day': 1,
            'year': -1472,
            'year_label': "1472 BCE",
            'title': "Create your own success with Hatshepsut",
            'cost': 2,
            'reward_raw': "\u4eba\u7269",
            'tokens': ["person"],
        },
        {
            'id': 6,
            'day': 1,
            'year': -500,
            'year_label': "500 BCE",
            'title': "Drink \"Hot Chocolate\" with the Mayans",
            'cost': 4,
            'reward_raw': "\u521b\u65b0+\u4e07\u80fd",
            'tokens': ["innovation", "wild"],
        },
        {
            'id': 7,
            'day': 1,
            'year': -708,
            'year_label': "708 BCE",
            'title': "Cheer at the Ancient Olympics",
            'cost': 2,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 8,
            'day': 1,
            'year': -506,
            'year_label': "506 BCE",
            'title': "Learn the Art of War from Sun Tzu",
            'cost': 2,
            'reward_raw': "\u4eba\u7269",
            'tokens': ["person"],
        },
        {
            'id': 9,
            'day': 1,
            'year': -450,
            'year_label': "450 BCE",
            'title': "Smelt iron with the Nigerian Nok",
            'cost': 4,
            'reward_raw': "\u521b\u65b0+\u8fdb\u6b65",
            'tokens': ["innovation", "progress"],
        },
        {
            'id': 10,
            'day': 1,
            'year': -347,
            'year_label': "347 BCE",
            'title': "Imagine a cave of shadows with Plato",
            'cost': 2,
            'reward_raw': "\u4eba\u7269",
            'tokens': ["person"],
        },
        {
            'id': 11,
            'day': 1,
            'year': -342,
            'year_label': "342 BCE",
            'title': "Hit the books with Alexander the Great",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u4e07\u80fd",
            'tokens': ["person", "wild"],
        },
        {
            'id': 12,
            'day': 1,
            'year': -221,
            'year_label': "221 BCE",
            'title': "Lay bricks on the Great Wall of China",
            'cost': 2,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 13,
            'day': 1,
            'year': -196,
            'year_label': "196 BCE",
            'title': "Help chisel the Rosetta Stone",
            'cost': 4,
            'reward_raw': "\u4e8b\u4ef6x2+\u521b\u65b0",
            'tokens': ["event", "event", "innovation"],
        },
        {
            'id': 14,
            'day': 1,
            'year': -49,
            'year_label': "49 BCE",
            'title': "Cross the Rubicon with Julius Caesar",
            'cost': 2,
            'reward_raw': "\u4eba\u7269",
            'tokens': ["person"],
        },
        {
            'id': 15,
            'day': 1,
            'year': -41,
            'year_label': "41 BCE",
            'title': "Admire Cleopatra's dramatic flair",
            'cost': 4,
            'reward_raw': "\u4eba\u7269+\u65f6\u95f4\u6c34\u6676x2",
            'tokens': ["person", "crystal", "crystal"],
        },
        {
            'id': 16,
            'day': 1,
            'year': 655,
            'year_label': "655 CE",
            'title': "Play the ancient sport of Ulama",
            'cost': 3,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 17,
            'day': 1,
            'year': 900,
            'year_label': "900 CE",
            'title': "Track the movement of Venus at Chichen Itza",
            'cost': 5,
            'reward_raw': "\u4e8b\u4ef6+\u8fdb\u6b65+\u65f6\u95f4\u6c34\u6676",
            'tokens': ["event", "progress", "crystal"],
        },
        {
            'id': 18,
            'day': 1,
            'year': 1110,
            'year_label': "1110 CE",
            'title': "Watch Emperor Song's grand fireworks show",
            'cost': 5,
            'reward_raw': "\u4e8b\u4ef6+\u521b\u65b0+\u65f6\u95f4\u6c34\u6676",
            'tokens': ["event", "innovation", "crystal"],
        },
        {
            'id': 19,
            'day': 1,
            'year': 1150,
            'year_label': "1150 CE",
            'title': "Carve intricate reliefs at Angkor Wat",
            'cost': 3,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 20,
            'day': 1,
            'year': 1230,
            'year_label': "1230 CE",
            'title': "Fire a medieval trebuchet",
            'cost': 3,
            'reward_raw': "\u521b\u65b0",
            'tokens': ["innovation"],
        },
        {
            'id': 21,
            'day': 1,
            'year': 1271,
            'year_label': "1271 CE",
            'title': "Travel the Silk Road with Marco Polo",
            'cost': 4,
            'reward_raw': "\u4eba\u7269x2+\u4e07\u80fd",
            'tokens': ["person", "person", "wild"],
        },
        {
            'id': 22,
            'day': 1,
            'year': 1300,
            'year_label': "1300 CE",
            'title': "Carve giant heads on Easter Island",
            'cost': 3,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 23,
            'day': 1,
            'year': 1385,
            'year_label': "1385 CE",
            'title': "Haggle at Great Zimbabwe",
            'cost': 3,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 24,
            'day': 1,
            'year': 1471,
            'year_label': "1471 CE",
            'title': "Discover the secrets of Machu Picchu",
            'cost': 4,
            'reward_raw': "\u4e8b\u4ef6+\u521b\u65b0+\u65f6\u95f4\u6c34\u6676",
            'tokens': ["event", "innovation", "crystal"],
        },
        {
            'id': 25,
            'day': 1,
            'year': 1504,
            'year_label': "1504 CE",
            'title': "Sculpt with Michelangelo",
            'cost': 2,
            'reward_raw': "\u4eba\u7269",
            'tokens': ["person"],
        },
        {
            'id': 26,
            'day': 1,
            'year': 1519,
            'year_label': "1519 CE",
            'title': "Sail the globe with Magellan",
            'cost': 4,
            'reward_raw': "\u4eba\u7269+\u8fdb\u6b65+\u4e07\u80fd",
            'tokens': ["person", "progress", "wild"],
        },
        {
            'id': 27,
            'day': 1,
            'year': 1587,
            'year_label': "1587 CE",
            'title': "Attend the Grand Kitano Tea Gathering",
            'cost': 5,
            'reward_raw': "\u4e8b\u4ef6+\u4e07\u80fd+\u65f6\u95f4\u6c34\u6676",
            'tokens': ["event", "wild", "crystal"],
        },
        {
            'id': 28,
            'day': 1,
            'year': 1629,
            'year_label': "1629 CE",
            'title': "Perform Kabuki theatre",
            'cost': 3,
            'reward_raw': "\u4e07\u80fd",
            'tokens': ["wild"],
        },
        {
            'id': 29,
            'day': 1,
            'year': 1690,
            'year_label': "1690 CE",
            'title': "Discuss revolutions with John Locke",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u8fdb\u6b65",
            'tokens': ["person", "progress"],
        },
        {
            'id': 30,
            'day': 1,
            'year': 1762,
            'year_label': "1762 CE",
            'title': "Take a bite of the first sandwich",
            'cost': 2,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 31,
            'day': 1,
            'year': 1794,
            'year_label': "1794 CE",
            'title': "Send a message with the semaphore",
            'cost': 1,
            'reward_raw': "\u521b\u65b0",
            'tokens': ["innovation"],
        },
        {
            'id': 32,
            'day': 1,
            'year': 1809,
            'year_label': "1809 CE",
            'title': "Command a huge pirate fleet with Cheng I Sao",
            'cost': 1,
            'reward_raw': "\u4eba\u7269",
            'tokens': ["person"],
        },
        {
            'id': 33,
            'day': 1,
            'year': 1829,
            'year_label': "1829 CE",
            'title': "Ride the \"Rocket\" with the Father of Railways",
            'cost': 2,
            'reward_raw': "\u4eba\u7269+\u521b\u65b0",
            'tokens': ["person", "innovation"],
        },
        {
            'id': 34,
            'day': 1,
            'year': 1850,
            'year_label': "1850 CE",
            'title': "Plan escape routes with Harriet Tubman",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u8fdb\u6b65",
            'tokens': ["person", "progress"],
        },
        {
            'id': 35,
            'day': 1,
            'year': 1891,
            'year_label': "1891 CE",
            'title': "Tour Tesla's lab",
            'cost': 4,
            'reward_raw': "\u4eba\u7269+\u521b\u65b0+\u4e07\u80fd",
            'tokens': ["person", "innovation", "wild"],
        },
        {
            'id': 36,
            'day': 1,
            'year': 1903,
            'year_label': "1903 CE",
            'title': "Fly with the Wright Brothers",
            'cost': 1,
            'reward_raw': "\u4eba\u7269x2",
            'tokens': ["person", "person"],
        },
        {
            'id': 37,
            'day': 1,
            'year': -3500,
            'year_label': "3500 BCE",
            'title': "Roll the first wheel",
            'cost': 4,
            'reward_raw': "\u521b\u65b0+\u8fdb\u6b65",
            'tokens': ["innovation", "progress"],
        },
        {
            'id': 38,
            'day': 1,
            'year': -2686,
            'year_label': "2686 BCE",
            'title': "Play senet with the Egyptians",
            'cost': 2,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 39,
            'day': 1,
            'year': -1300,
            'year_label': "1300 BCE",
            'title': "Barbecue with the Mycenaeans",
            'cost': 2,
            'reward_raw': "\u4eba\u7269x2+\u4e8b\u4ef6",
            'tokens': ["person", "person", "event"],
        },
        {
            'id': 40,
            'day': 1,
            'year': -528,
            'year_label': "528 BCE",
            'title': "Meditate with the Buddha",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u4e07\u80fd",
            'tokens': ["person", "wild"],
        },
    ],
    2: [
        {
            'id': 41,
            'day': 2,
            'year': -520,
            'year_label': "520 BCE",
            'title': "Expand your mind with Confucius",
            'cost': 2,
            'reward_raw': "\u4eba\u7269",
            'tokens': ["person"],
        },
        {
            'id': 42,
            'day': 2,
            'year': -400,
            'year_label': "400 BCE",
            'title': "Hunt with the real Amazonian women",
            'cost': 4,
            'reward_raw': "\u4e8b\u4ef6+\u521b\u65b0+\u4e07\u80fd",
            'tokens': ["event", "innovation", "wild"],
        },
        {
            'id': 43,
            'day': 2,
            'year': -377,
            'year_label': "377 BCE",
            'title': "Study medicine with Hippocrates",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u521b\u65b0",
            'tokens': ["person", "innovation"],
        },
        {
            'id': 44,
            'day': 2,
            'year': -332,
            'year_label': "332 BCE",
            'title': "Dock at the port of Carthage",
            'cost': 2,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 45,
            'day': 2,
            'year': -230,
            'year_label': "230 BCE",
            'title': "Sail under the Colossus of Rhodes",
            'cost': 2,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 46,
            'day': 2,
            'year': -194,
            'year_label': "194 BCE",
            'title': "Study at the Great Library of Alexandria",
            'cost': 2,
            'reward_raw': "\u521b\u65b0",
            'tokens': ["innovation"],
        },
        {
            'id': 47,
            'day': 2,
            'year': 40,
            'year_label': "40 CE",
            'title': "Save Vietnam with the Trung Sisters",
            'cost': 4,
            'reward_raw': "\u4eba\u7269x2+\u8fdb\u6b65",
            'tokens': ["person", "person", "progress"],
        },
        {
            'id': 48,
            'day': 2,
            'year': 980,
            'year_label': "980 CE",
            'title': "Discover Iceland with the Vikings",
            'cost': 2,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 49,
            'day': 2,
            'year': 1195,
            'year_label': "1195 CE",
            'title': "Surf with the Polynesians",
            'cost': 3,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 50,
            'day': 2,
            'year': 1280,
            'year_label': "1280 CE",
            'title': "Wrestle with Khutulun",
            'cost': 4,
            'reward_raw': "\u4eba\u7269+\u4e07\u80fd",
            'tokens': ["person", "wild"],
        },
        {
            'id': 51,
            'day': 2,
            'year': 1324,
            'year_label': "1324 CE",
            'title': "Give away untold riches with Mansa Musa",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u65f6\u95f4\u6c34\u6676",
            'tokens': ["person", "crystal"],
        },
        {
            'id': 52,
            'day': 2,
            'year': 1429,
            'year_label': "1429 CE",
            'title': "March with Joan of Arc",
            'cost': 5,
            'reward_raw': "\u8fdb\u6b65+\u4e07\u80fd+\u65f6\u95f4\u6c34\u6676",
            'tokens': ["progress", "wild", "crystal"],
        },
        {
            'id': 53,
            'day': 2,
            'year': 1493,
            'year_label': "1493 CE",
            'title': "Seek scholarly advice at Timbuktu",
            'cost': 4,
            'reward_raw': "\u4e8b\u4ef6+\u521b\u65b0",
            'tokens': ["event", "innovation"],
        },
        {
            'id': 54,
            'day': 2,
            'year': 1507,
            'year_label': "1507 CE",
            'title': "Observe the Dodo bird on Mauritius Island",
            'cost': 3,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 55,
            'day': 2,
            'year': 1564,
            'year_label': "1564 CE",
            'title': "Throw dice with Gerolamo Cardano",
            'cost': 3,
            'reward_raw': "\u521b\u65b0",
            'tokens': ["innovation"],
        },
        {
            'id': 56,
            'day': 2,
            'year': 1601,
            'year_label': "1601 CE",
            'title': "Write a play with William Shakespeare",
            'cost': 5,
            'reward_raw': "\u4eba\u7269+\u4e07\u80fd+\u65f6\u95f4\u6c34\u6676",
            'tokens': ["person", "wild", "crystal"],
        },
        {
            'id': 57,
            'day': 2,
            'year': 1640,
            'year_label': "1640 CE",
            'title': "Study the blade with a Samurai",
            'cost': 4,
            'reward_raw': "\u4eba\u7269+\u4e07\u80fd",
            'tokens': ["person", "wild"],
        },
        {
            'id': 58,
            'day': 2,
            'year': 1717,
            'year_label': "1717 CE",
            'title': "Hear Johann Sebastian Bach Perform",
            'cost': 3,
            'reward_raw': "\u521b\u65b0+\u4eba\u7269+\u65f6\u95f4\u6c34\u6676",
            'tokens': ["innovation", "person", "crystal"],
        },
        {
            'id': 59,
            'day': 2,
            'year': 1776,
            'year_label': "1776 CE",
            'title': "See the signing of the Declaration of Independence",
            'cost': 5,
            'reward_raw': "\u4e8b\u4ef6+\u8fdb\u6b65+\u65f6\u95f4\u6c34\u6676",
            'tokens': ["event", "progress", "crystal"],
        },
        {
            'id': 60,
            'day': 2,
            'year': 1835,
            'year_label': "1835 CE",
            'title': "Sail the Galapagos Islands with Charles Darwin",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u521b\u65b0",
            'tokens': ["person", "innovation"],
        },
        {
            'id': 61,
            'day': 2,
            'year': 1863,
            'year_label': "1863 CE",
            'title': "Hear the Gettysburg Address",
            'cost': 2,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 62,
            'day': 2,
            'year': 1893,
            'year_label': "1893 CE",
            'title': "Ride the ferris wheel at the World's Fair",
            'cost': 2,
            'reward_raw': "\u4eba\u7269x2+\u521b\u65b0",
            'tokens': ["person", "person", "innovation"],
        },
        {
            'id': 63,
            'day': 2,
            'year': 1905,
            'year_label': "1905 CE",
            'title': "Study relativity with Albert Einstein",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u521b\u65b0",
            'tokens': ["person", "innovation"],
        },
        {
            'id': 64,
            'day': 2,
            'year': 1914,
            'year_label': "1914 CE",
            'title': "Practice Suffrajitsu",
            'cost': 4,
            'reward_raw': "\u4e8b\u4ef6x2+\u4e07\u80fd",
            'tokens': ["event", "event", "wild"],
        },
        {
            'id': 65,
            'day': 2,
            'year': 1918,
            'year_label': "1918 CE",
            'title': "Read braille with Helen Keller",
            'cost': 2,
            'reward_raw': "\u4eba\u7269",
            'tokens': ["person"],
        },
        {
            'id': 66,
            'day': 2,
            'year': 1930,
            'year_label': "1930 CE",
            'title': "March to the salt works with Gandhi",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u8fdb\u6b65",
            'tokens': ["person", "progress"],
        },
        {
            'id': 67,
            'day': 2,
            'year': 1933,
            'year_label': "1933 CE",
            'title': "Stretch with Krishnamacharya",
            'cost': 2,
            'reward_raw': "\u4e07\u80fd",
            'tokens': ["wild"],
        },
        {
            'id': 68,
            'day': 2,
            'year': 1951,
            'year_label': "1951 CE",
            'title': "Dance ballet with Maria Tallchief",
            'cost': 1,
            'reward_raw': "\u4eba\u7269",
            'tokens': ["person"],
        },
        {
            'id': 69,
            'day': 2,
            'year': 1953,
            'year_label': "1953 CE",
            'title': "See DNA more clearly with Rosalind Franklin",
            'cost': 4,
            'reward_raw': "\u4eba\u7269+\u521b\u65b0+\u8fdb\u6b65",
            'tokens': ["person", "innovation", "progress"],
        },
        {
            'id': 70,
            'day': 2,
            'year': 1960,
            'year_label': "1960 CE",
            'title': "Study chimpanzees with Jane Goodall",
            'cost': 1,
            'reward_raw': "\u4eba\u7269",
            'tokens': ["person"],
        },
        {
            'id': 71,
            'day': 2,
            'year': 1963,
            'year_label': "1963 CE",
            'title': "Share a dream with Martin Luther King Jr.",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u8fdb\u6b65",
            'tokens': ["person", "progress"],
        },
        {
            'id': 72,
            'day': 2,
            'year': 1985,
            'year_label': "1985 CE",
            'title': "Rock out at Live Aid",
            'cost': 1,
            'reward_raw': "\u4eba\u7269+\u4e8b\u4ef6",
            'tokens': ["person", "event"],
        },
        {
            'id': 73,
            'day': 2,
            'year': -70,
            'year_label': "70 BCE",
            'title': "Shop at the markets of Petra",
            'cost': 2,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 74,
            'day': 2,
            'year': 124,
            'year_label': "124 CE",
            'title': "Race a chariot",
            'cost': 2,
            'reward_raw': "\u521b\u65b0",
            'tokens': ["innovation"],
        },
        {
            'id': 75,
            'day': 2,
            'year': 998,
            'year_label': "998 CE",
            'title': "Learn from the polymath Avicenna",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u521b\u65b0",
            'tokens': ["person", "innovation"],
        },
        {
            'id': 76,
            'day': 2,
            'year': 1209,
            'year_label': "1209 CE",
            'title': "Ride with Genghis Khan",
            'cost': 2,
            'reward_raw': "\u4eba\u7269",
            'tokens': ["person"],
        },
        {
            'id': 77,
            'day': 2,
            'year': 1330,
            'year_label': "1330 CE",
            'title': "Paddle a Maori War Canoe",
            'cost': 2,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 78,
            'day': 2,
            'year': 1455,
            'year_label': "1455 CE",
            'title': "Work the Gutenberg Press",
            'cost': 4,
            'reward_raw': "\u521b\u65b0+\u8fdb\u6b65",
            'tokens': ["innovation", "progress"],
        },
        {
            'id': 79,
            'day': 2,
            'year': 1503,
            'year_label': "1503 CE",
            'title': "Paint with Leonardo da Vinci",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u8fdb\u6b65",
            'tokens': ["person", "progress"],
        },
        {
            'id': 80,
            'day': 2,
            'year': 1510,
            'year_label': "1510 CE",
            'title': "Paddle the causeways of Tenochtitlan",
            'cost': 4,
            'reward_raw': "\u4e8b\u4ef6+\u4e07\u80fd",
            'tokens': ["event", "wild"],
        },
    ],
    3: [
        {
            'id': 81,
            'day': 3,
            'year': 1581,
            'year_label': "1581 CE",
            'title': "Joust at the Accession Day tilt",
            'cost': 2,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 82,
            'day': 3,
            'year': 1610,
            'year_label': "1610 CE",
            'title': "Discover Jupiter's moons with Galileo",
            'cost': 2,
            'reward_raw': "\u4e8b\u4ef6+\u4eba\u7269",
            'tokens': ["event", "person"],
        },
        {
            'id': 83,
            'day': 3,
            'year': 1666,
            'year_label': "1666 CE",
            'title': "Stroll through Isaac Newton's Apple Orchard",
            'cost': 4,
            'reward_raw': "\u521b\u65b0+\u8fdb\u6b65",
            'tokens': ["innovation", "progress"],
        },
        {
            'id': 84,
            'day': 3,
            'year': 1752,
            'year_label': "1752 CE",
            'title': "Fly a kite with Benjamin Franklin",
            'cost': 2,
            'reward_raw': "\u4eba\u7269",
            'tokens': ["person"],
        },
        {
            'id': 85,
            'day': 3,
            'year': 1785,
            'year_label': "1785 CE",
            'title': "Fly a hot air balloon across the English Channel",
            'cost': 5,
            'reward_raw': "\u4e8b\u4ef6+\u4e07\u80fd+\u65f6\u95f4\u6c34\u6676",
            'tokens': ["event", "wild", "crystal"],
        },
        {
            'id': 86,
            'day': 3,
            'year': 1801,
            'year_label': "1801 CE",
            'title': "Help free Haiti with Toussaint Louverture",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u4e8b\u4ef6",
            'tokens': ["person", "event"],
        },
        {
            'id': 87,
            'day': 3,
            'year': 1805,
            'year_label': "1805 CE",
            'title': "Explore the Louisiana Territory with Sacagawea",
            'cost': 4,
            'reward_raw': "\u4eba\u7269+\u4e07\u80fd",
            'tokens': ["person", "wild"],
        },
        {
            'id': 88,
            'day': 3,
            'year': 1815,
            'year_label': "1815 CE",
            'title': "See if you're taller than Napoleon Bonaparte",
            'cost': 4,
            'reward_raw': "\u4eba\u7269+\u4e8b\u4ef6+\u8fdb\u6b65",
            'tokens': ["person", "event", "progress"],
        },
        {
            'id': 89,
            'day': 3,
            'year': 1823,
            'year_label': "1823 CE",
            'title': "Hunt fossils with Mary Anning",
            'cost': 5,
            'reward_raw': "\u521b\u65b0+\u4e07\u80fd+\u65f6\u95f4\u6c34\u6676",
            'tokens': ["innovation", "wild", "crystal"],
        },
        {
            'id': 90,
            'day': 3,
            'year': 1843,
            'year_label': "1843 CE",
            'title': "Talk computers with the Countess of Lovelace",
            'cost': 3,
            'reward_raw': "\u4e8b\u4ef6+\u4eba\u7269+\u521b\u65b0",
            'tokens': ["event", "person", "innovation"],
        },
        {
            'id': 91,
            'day': 3,
            'year': 1849,
            'year_label': "1849 CE",
            'title': "Strike it rich in the Gold Rush",
            'cost': 5,
            'reward_raw': "\u4e8b\u4ef6+\u4e07\u80fd+\u65f6\u95f4\u6c34\u6676",
            'tokens': ["event", "wild", "crystal"],
        },
        {
            'id': 92,
            'day': 3,
            'year': 1869,
            'year_label': "1869 CE",
            'title': "Raft the Colorado River with John Powell",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u4e8b\u4ef6",
            'tokens': ["person", "event"],
        },
        {
            'id': 93,
            'day': 3,
            'year': 1889,
            'year_label': "1889 CE",
            'title': "Trek the world with Nellie Bly",
            'cost': 4,
            'reward_raw': "\u4eba\u7269+\u4e8b\u4ef6+\u65f6\u95f4\u6c34\u6676",
            'tokens': ["person", "event", "crystal"],
        },
        {
            'id': 94,
            'day': 3,
            'year': 1894,
            'year_label': "1894 CE",
            'title': "Race in the Paris\u2013Rouen",
            'cost': 3,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 95,
            'day': 3,
            'year': 1901,
            'year_label': "1901 CE",
            'title': "Catch a Vaudeville show",
            'cost': 3,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 96,
            'day': 3,
            'year': 1909,
            'year_label': "1909 CE",
            'title': "Be psychoanalyzed by Sigmund Freud",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u521b\u65b0",
            'tokens': ["person", "innovation"],
        },
        {
            'id': 97,
            'day': 3,
            'year': 1911,
            'year_label': "1911 CE",
            'title': "Advance chemistry with Marie Curie",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u521b\u65b0",
            'tokens': ["person", "innovation"],
        },
        {
            'id': 98,
            'day': 3,
            'year': 1923,
            'year_label': "1923 CE",
            'title': "Excavate King Tut's tomb",
            'cost': 4,
            'reward_raw': "\u4e8b\u4ef6+\u4e07\u80fd",
            'tokens': ["event", "wild"],
        },
        {
            'id': 99,
            'day': 3,
            'year': 1925,
            'year_label': "1925 CE",
            'title': "Pet the loyal dog Hachik\u014d",
            'cost': 2,
            'reward_raw': "\u4e8b\u4ef6",
            'tokens': ["event"],
        },
        {
            'id': 100,
            'day': 3,
            'year': 1942,
            'year_label': "1942 CE",
            'title': "Crack codes with Alan Turing",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u65f6\u95f4\u6c34\u6676",
            'tokens': ["person", "crystal"],
        },
        {
            'id': 101,
            'day': 3,
            'year': 1947,
            'year_label': "1947 CE",
            'title': "Break the sound barrier with Chuck Yeager",
            'cost': 4,
            'reward_raw': "\u4e07\u80fd+\u65f6\u95f4\u6c34\u6676",
            'tokens': ["wild", "crystal"],
        },
        {
            'id': 102,
            'day': 3,
            'year': 1955,
            'year_label': "1955 CE",
            'title': "Boycott busses with Rosa Parks",
            'cost': 3,
            'reward_raw': "\u4eba\u7269+\u8fdb\u6b65",
            'tokens': ["person", "progress"],
        },
        {
            'id': 103,
            'day': 3,
            'year': 1959,
            'year_label': "1959 CE",
            'title': "Explore the ocean with Jacque Cousteau",
            'cost': 2,
            'reward_raw': "\u4eba\u7269+\u521b\u65b0",
            'tokens': ["person", "innovation"],
        },
        {
            'id': 104,
            'day': 3,
            'year': 1969,
            'year_label': "1969 CE",
            'title': "Moonwalk with the Apollo 11 crew",
            'cost': 2,
            'reward_raw': "\u8fdb\u6b65",
            'tokens': ["progress"],
        },
        {
            'id': 105,
            'day': 3,
            'year': 1977,
            'year_label': "1977 CE",
            'title': "Reforest the earth with Wangari Maathai",
            'cost': 1,
            'reward_raw': "\u4eba\u7269",
            'tokens': ["person"],
        },
        {
            'id': 106,
            'day': 3,
            'year': 1989,
            'year_label': "1989 CE",
            'title': "Tear down the Berlin Wall",
            'cost': 2,
            'reward_raw': "\u8fdb\u6b65",
            'tokens': ["progress"],
        },
        {
            'id': 107,
            'day': 3,
            'year': 1990,
            'year_label': "1990 CE",
            'title': "Excavate the T-Rex \"Sue\"",
            'cost': 1,
            'reward_raw': "\u4eba\u7269+\u521b\u65b0",
            'tokens': ["person", "innovation"],
        },
        {
            'id': 108,
            'day': 3,
            'year': 1994,
            'year_label': "1994 CE",
            'title': "Cast your vote for Nelson Mandela",
            'cost': 1,
            'reward_raw': "\u4eba\u7269",
            'tokens': ["person"],
        },
    ],
}

ALL_CARDS = [card for day in sorted(DAY_DECKS) for card in DAY_DECKS[day]]
